import {beforeAll,expect,it} from 'vitest';
import {scanProjectFiles} from '../scan';
import {semanticInput} from './client';
import {analyzeSemanticSources} from './analyze';
import {initializeTestParser,testLanguage,testParser} from './testRuntime';
import {architectureSimpleOverview} from './architectureSimple';
import {prepareArchitectureScope} from './architectureProjection';
import {staticNodeScript} from '../staticNodeScript';
beforeAll(initializeTestParser);
const scan=async(sources:Record<string,string>)=>{const store=await scanProjectFiles(Object.entries(sources).map(([relativePath,source])=>({relativePath,name:relativePath.split('/').at(-1)!,extension:'.'+relativePath.split('.').at(-1),size:source.length,readText:async()=>source})));return {store,model:(await analyzeSemanticSources(semanticInput(store),testLanguage,undefined,testParser)).architecture!};};
const site={'index.html':'<!doctype html><html><head><link rel="stylesheet" href="./paint.css"></head><body><script src="./ui.js"></script></body></html>','ui.js':'console.log("browser");','paint.css':'body{color:white}'};
const serve=`import{createServer}from'node:http';import{readFile}from'node:fs/promises';import{resolve,dirname}from'node:path';import{fileURLToPath}from'node:url';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..'),host=process.env.HOST||'127.0.0.1',port=Number(process.env.PORT||5173);
async function handler(req,res){const url=new URL(req.url,'http://localhost');const file=resolve(root,'.'+url.pathname);res.end(await readFile(file));}
const server=createServer(handler);server.listen(port,host);`;
const build=`import{readFileSync,writeFileSync}from'node:fs';import{resolve,dirname}from'node:path';import{fileURLToPath}from'node:url';const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
let html=readFileSync(resolve(root,'index.html'),'utf8');html=html.replace('old','new');writeFileSync(resolve(root,'index.html'),html);
const code=readFileSync(resolve(root,'ui.js'),'utf8');writeFileSync(resolve(root,'generated.js'),code.replace('a','b'));
const target=process.argv[2]?resolve(process.argv[2]):resolve(root,'../preview.html');writeFileSync(target,html+code);`;
const project=(scripts:Record<string,string>,more:Record<string,string>={})=>({...site,'package.json':JSON.stringify({name:'renamable',scripts}),'tools/http.mjs':serve,'tools/output.mjs':build,...more});
it('recognizes an HTML/JS/CSS-only site without operations or external targets',async()=>{const {model}=await scan(site);const app=model.nodes.find(n=>n.architecture?.kind==='application')!;expect(app.architecture?.entryPaths).toEqual(['index.html']);expect(app.architecture?.context).toContain('静的Webサイト・ブラウザ実行');expect(model.nodes.some(n=>n.architecture?.kind==='tool-operation')).toBe(false);expect(model.edges.some(e=>e.kind==='flow-deploys')).toBe(false);expect(architectureSimpleOverview(prepareArchitectureScope(model)).graph.nodes).toHaveLength(1);});
it.each(['test','fixtures','templates','docs'])('does not identify %s HTML as a site',async folder=>{const {model}=await scan(Object.fromEntries(Object.entries(site).map(([p,s])=>[folder+'/'+p,s])));expect(model.nodes.some(n=>n.attributes.staticSite)).toBe(false);});
it('does not classify file-writing CLI as browser site',async()=>{const {model}=await scan({'package.json':JSON.stringify({bin:'main.js',scripts:{build:'node main.js'}}),'main.js':"import{readFileSync,writeFileSync}from'node:fs';writeFileSync('log.txt',readFileSync('input.txt'))"});expect(model.nodes.some(n=>n.attributes.staticSite||n.attributes.customStaticOperation)).toBe(false);});
it.each<Record<string,string>>([{start:'node tools/http.mjs'},{preview:'node tools/output.mjs'}])('keeps serving and generation independent: %j',async scripts=>{const {model}=await scan(project(scripts));expect(model.nodes.filter(n=>n.architecture?.kind==='tool-operation'&&n.attributes.purpose!=='script')).toHaveLength(1);expect(model.edges.some(e=>e.kind==='flow-precedes'||e.kind==='flow-deploys')).toBe(false);expect(model.nodes.filter(n=>n.architecture?.kind==='application')).toHaveLength(1);});
it('traces actual response, root, host/port defaults; not URL base or Vite',async()=>{const {model}=await scan(project({go:'node tools/http.mjs'}));const runtime=model.nodes.find(n=>n.architecture?.kind==='execution-config')!;expect(runtime.attributes.providedContent).toContain('127.0.0.1:5173');expect(JSON.stringify(runtime.attributes.customStaticDetails)).toContain('上書きは未取得');expect(runtime.architecture?.environments).toEqual([]);expect(model.nodes.some(n=>n.attributes.dictionaryStackId==='vite')).toBe(false);expect(runtime.evidence.map(e=>e.path)).toEqual(expect.arrayContaining(['package.json','tools/http.mjs']));});
it.each([serve.replace('res.end(await readFile(file))',"res.end('hello')"),serve.replace('server.listen(port,host)','other.listen(port,host)'),serve.replace("const root=resolve(dirname(fileURLToPath(import.meta.url)),'..')","const root=resolve(dirname(fileURLToPath(import.meta.url)),'../other')")])('does not invent static serving from partial evidence',async code=>{const {model}=await scan(project({go:'node tools/http.mjs'},{'tools/http.mjs':code}));expect(model.edges.some(e=>e.kind==='flow-starts')).toBe(false);});
it('keeps updates, split outputs and external default preview path plus their original evidence',async()=>{const {model}=await scan(project({start:'node tools/http.mjs',bundle:'node tools/output.mjs'}));const outputs=model.nodes.filter(n=>n.attributes.customStaticOutput);expect(outputs).toHaveLength(2);expect(outputs.flatMap(n=>n.attributes.outputPaths)).toEqual(expect.arrayContaining(['index.html','generated.js','../preview.html']));expect(JSON.stringify(outputs)).toContain('更新：index.html');expect(model.edges.some(e=>e.kind==='flow-precedes')).toBe(false);const simple=architectureSimpleOverview(prepareArchitectureScope(model));expect(simple.graph.nodes).toHaveLength(6);expect(simple.graph.edges).toHaveLength(5);expect([...simple.owners.keys()].sort()).toEqual(model.nodes.map(n=>n.id).sort());});
it('resolves explicit output argument, with subdirectory cwd only once',()=>{const facts=staticNodeScript('sub/tools/a.mjs',build,'sub',['custom.html']);expect(facts.writes.flatMap(w=>w.output.values)).toEqual(['sub/index.html','sub/generated.js','sub/custom.html']);});
it('keeps dynamically unresolved destination beside proven outputs',()=>{const facts=staticNodeScript('tools/a.mjs',build.replace("process.argv[2]?resolve(process.argv[2]):resolve(root,'../preview.html')",'getDestination()'),'.');expect(facts.writes).toHaveLength(3);expect(facts.writes[2]!.output.unknown).toBe(true);expect(facts.writes[2]!.output.values).toEqual([]);});
it('ignores uncalled, conditional and constant/log writes',()=>{const facts=staticNodeScript('tools/a.mjs',"import{readFileSync,writeFileSync}from'node:fs';function never(){writeFileSync('out.html',readFileSync('in.html'))}if(flag)writeFileSync('other.html',readFileSync('in.html'));writeFileSync('log.txt',readFileSync('in.html'));writeFileSync('constant.js','x');",'.');expect(facts.writes).toEqual([]);});
it('does not identify locally shadowed APIs or a test import as another server',async()=>{const code=serve.replace('res.end(await readFile(file))',"const readFile=async()=>'';res.end(await readFile(file))");expect(staticNodeScript('tools/http.mjs',code,'.').servers).toEqual([]);const {model}=await scan(project({start:'node tools/http.mjs',test:'node --test tests/a.mjs'},{'tests/a.mjs':"import{handler}from'../tools/http.mjs';export async function probe(){const base=unknown();return await fetch(base+'/');}"}));expect(model.nodes.filter(n=>n.architecture?.kind==='execution-config')).toHaveLength(1);const testComponent=model.nodes.find(n=>n.architecture?.kind==='component'&&n.architecture.files.includes('tests/a.mjs'));expect(testComponent?.architecture?.auxiliary).toBe(true);});
it('records document destination without deploy/HTTP edges and ignores explanatory sections',async()=>{const {model}=await scan(project({}, {'README.md':'# Site\n## DEPLOYMENT\nhttps://author.github.io/sample/\n## Documentation\nhttps://docs.example/\n![badge](https://badge.example/)'}));const app=model.nodes.find(n=>n.attributes.staticSite)!;expect(app.attributes.documentedDestinations).toHaveLength(1);expect(app.evidence.some(e=>e.path==='README.md'&&e.line===3)).toBe(true);expect(model.edges.some(e=>['http-request','flow-deploys'].includes(e.kind))).toBe(false);const none=await scan(project({}, {'README.md':'# Site\n## Demo\nhttps://demo.example/\n## Documentation\nhttps://docs.example/'}));expect(none.model.nodes.some(n=>n.attributes.documentedDestinations)).toBe(false);});
it('preserves known Vite operation and adds only an uncovered custom operation',async()=>{const {model}=await scan(project({}, {'package.json':JSON.stringify({scripts:{dev:'vite',bundle:'node tools/output.mjs'},devDependencies:{vite:'7.1.0'}})}));expect(model.nodes.filter(n=>n.architecture?.kind==='tool-operation'&&n.attributes.purpose!=='script')).toHaveLength(2);expect(model.nodes.filter(n=>n.attributes.dictionaryStackId==='vite'&&n.architecture?.kind==='tool-operation')).toHaveLength(1);});
it('uses finite arrays and member writes as original input dependencies',()=>{const source="import{readFileSync,writeFileSync}from'node:fs';import{resolve}from'node:path';const data=JSON.parse(readFileSync('data.json'));data.extra=JSON.parse(readFileSync('extra.json'));writeFileSync('out.js',JSON.stringify(data));const parts=['a','b'];let bundle='';for(const part of parts)bundle+=readFileSync(resolve('src',`${part}.js`));writeFileSync('all.js',bundle);";const facts=staticNodeScript('build.mjs',source,'.');expect(facts.writes[0]!.inputs).toEqual(['data.json','extra.json']);expect(facts.writes[1]!.inputs).toEqual(['src/a.js','src/b.js']);});
it('does not classify a template expression as an HTML entry',async()=>{const {model}=await scan({...site,'index.html':site['index.html'].replace('<body>','<body>{{ template }}')});expect(model.nodes.some(n=>n.attributes.staticSite)).toBe(false);});
it('handles cycles and unknown host/port without guessed defaults',()=>{const cyclic=build.replace("const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');",'const root=other,other=root;');expect(staticNodeScript('tools/a.mjs',cyclic,'.').writes.every(w=>w.output.unknown)).toBe(true);const server=staticNodeScript('tools/http.mjs',serve.replace("process.env.HOST||'127.0.0.1'",'getHost()').replace('Number(process.env.PORT||5173)','getPort()'),'.').servers[0]!;expect(server.host.values).toEqual([]);expect(server.port.values).toEqual([]);});

it('recognizes renamed project, HTML entry, scripts and source directories',async()=>{const sources=project({watch:'node tools/http.mjs',assemble:'node tools/output.mjs'});const renamed=Object.fromEntries(Object.entries(sources).map(([p,s])=>['nested/'+p.replace('tools/http.mjs','ops/local.mjs').replace('tools/output.mjs','ops/assemble.mjs').replace('index.html','home.html'),s.replaceAll('tools/http.mjs','ops/local.mjs').replaceAll('tools/output.mjs','ops/assemble.mjs').replaceAll('index.html','home.html').replaceAll('renamable','another-name')]));const {model}=await scan(renamed);expect(model.nodes.filter(n=>n.attributes.customStaticOperation)).toHaveLength(2);expect(model.nodes.find(n=>n.attributes.staticSite)?.architecture?.entryPaths).toEqual(expect.arrayContaining(['nested/home.html']));expect(model.nodes.flatMap(n=>n.attributes.outputPaths??[])).toContain('preview.html');});
it('does not treat a cache write or docs link in a deployment section as a build/destination',async()=>{const {model}=await scan(project({build:'node tools/cache.mjs'},{'tools/cache.mjs':"import{readFileSync,writeFileSync}from'node:fs';writeFileSync('.cache/memory.js',readFileSync('ui.js'));",'README.md':'## DEPLOYMENT\n[Documentation](https://docs.example/)\nSee https://example.com for instructions.\n![badge](https://badge.example/)'}));expect(model.nodes.some(n=>n.attributes.customStaticOperation||n.attributes.documentedDestinations)).toBe(false);});

it('keeps an uncalled/conditional server out, accepting only a proven direct-entry guard',()=>{const split=serve.indexOf('const server='),head=serve.slice(0,split),body=serve.slice(split);for(const wrapper of [`function never(){${body}}`,`if(unknownFlag){${body}}`,`if(false){${body}}`])expect(staticNodeScript('tools/http.mjs',head+wrapper,'.').servers).toEqual([]);expect(staticNodeScript('tools/http.mjs',head+`if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){${body}}`,'.').servers).toHaveLength(1);});
it('retains literal and explicit argument host/port without guessing unavailable arguments',()=>{const code=serve.replace("process.env.HOST||'127.0.0.1'","process.argv[3]||'127.0.0.1'").replace('process.env.PORT||5173','process.argv[2]||5173');const server=staticNodeScript('tools/http.mjs',code,'.',['8081','0.0.0.0']).servers[0]!;expect(server.port.values).toEqual(['8081']);expect(server.host.values).toEqual(['0.0.0.0']);const literal=staticNodeScript('tools/http.mjs',serve.replace('Number(process.env.PORT||5173)','8082').replace("process.env.HOST||'127.0.0.1'","'localhost'"),'.').servers[0]!;expect(literal.port.values).toEqual(['8082']);expect(literal.host.values).toEqual(['localhost']);});

it('does not interpret arbitrary custom-script flags as deployment environment names',async()=>{const {model}=await scan(project({start:'node tools/http.mjs --mode production --env live'}));const op=model.nodes.find(n=>n.attributes.customStaticOperation)!;expect(op.architecture?.environments).toEqual([]);expect(op.attributes.usageArguments).toContain('--env live');expect(op.attributes.dictionaryStackId).toBe('nodejs');});
