import {writeFileSync} from 'node:fs';
import {beforeAll,expect,it} from 'vitest';
import {scanProjectFiles} from '../scan';
import {semanticInput} from './client';
import {analyzeSemanticSources} from './analyze';
import {initializeTestParser,testLanguage,testParser} from './testRuntime';
import {architectureSimpleOverview} from './architectureSimple';
import {prepareArchitectureScope} from './architectureProjection';
import {layoutSimpleArchitecture} from './architectureSimpleLayout';
import type {SemanticNode,SemanticGraph} from './types';
beforeAll(initializeTestParser);
const scan=async(sources:Record<string,string>)=>{const store=await scanProjectFiles(Object.entries(sources).map(([relativePath,source])=>({relativePath,name:relativePath.split('/').at(-1)!,extension:'.'+relativePath.split('.').at(-1),size:source.length,readText:async()=>source})));return {store,input:semanticInput(store),model:(await analyzeSemanticSources(semanticInput(store),testLanguage,undefined,testParser)).architecture!};};
const nextSources=(scripts:Record<string,string>,config='const settings = {}; export default settings;')=>({'package.json':JSON.stringify({name:'renamable',scripts,dependencies:{next:'16.2.9',react:'19'}}),'next.config.ts':config,'app/page.tsx':'export default function Page(){return <div>Hello</div>}'});
it('reuses script calls and keeps Next mode separate from deployment environments',async()=>{
 const {model,input}=await scan(nextSources({dev:'next dev',build:'next build',start:'next start',wrapper:'npm run dev'}));expect(input.commands!.some(c=>c.argv[0]==='next')).toBe(true);
 const operations=model.nodes.filter(n=>n.attributes.dictionaryStackId==='nextjs'&&n.architecture?.kind==='tool-operation');expect(operations).toHaveLength(3);expect(operations.every(n=>!n.architecture?.environments.length)).toBe(true);expect(model.edges.filter(e=>e.kind==='flow-starts')).toHaveLength(2);expect(model.edges.some(e=>e.kind==='flow-invokes')).toBe(true);
 const build=model.nodes.find(n=>n.attributes.artifactPath==='.next')!;expect(build).toBeDefined();expect(model.edges.some(e=>e.target===build.id&&e.kind==='flow-generates')).toBe(true);expect(model.edges.some(e=>e.source===build.id&&e.kind==='flow-input')).toBe(true);expect(model.nodes.filter(n=>n.architecture?.kind==='application')).toHaveLength(1);expect(model.nodes.some(n=>/Vercel|Marketplace/.test(n.label))).toBe(false);
 const before=JSON.stringify(model),simple=architectureSimpleOverview(prepareArchitectureScope(model));expect(simple.graph.nodes.some(n=>n.label.includes('Next.js'))).toBe(true);expect(JSON.stringify(model)).toBe(before);
});
it.each(['export','standalone'])('retains output mode %s without fabricating a server launch',async output=>{const {model}=await scan(nextSources({build:'next build',start:'next start'},`export default {output:'${output}'}`));expect(model.nodes.find(n=>n.attributes.artifactPath===(output==='export'?'out':'.next'))).toBeDefined();expect(model.edges.some(e=>e.kind==='flow-starts')).toBe(false);});
it.each(['export default ()=>({distDir:"hidden"})','export default {...unknown}','const x={}; x.distDir=unknown; export default x;'])('retains input without guessing dynamic output: %s',async config=>{const {model}=await scan(nextSources({build:'next build'},config));expect(model.nodes.some(n=>n.attributes.purpose==='build')).toBe(true);expect(model.edges.some(e=>e.kind==='flow-generates')).toBe(false);});
it('does not create operations from dependencies alone and supports build-only explicit output',async()=>{const none=await scan(nextSources({}));expect(none.model.nodes.some(n=>n.architecture?.kind==='tool-operation')).toBe(false);const {model}=await scan(nextSources({only:'next build'},'module.exports={distDir:"custom"};'));expect(model.nodes.some(n=>n.attributes.artifactPath==='custom')).toBe(true);expect(model.edges.some(e=>e.kind==='flow-starts')).toBe(false);});
it.each(["import {build as bundle} from 'esbuild';", "const {build:bundle}=require('esbuild');"])('binds Node build files through static declarations: %s',async prefix=>{
 const {model}=await scan({'package.json':JSON.stringify({name:'extension',engines:{vscode:'^1'},main:'out/extension.js',scripts:{build:'node tools/bundle.cjs'},devDependencies:{esbuild:'0.25'}}),'tools/bundle.cjs':prefix+"await bundle({entryPoints:['code/start.ts'],outfile:'out/extension.js'});",'code/start.ts':'export function activate(){}'});
 const output=model.nodes.find(n=>n.attributes.artifactPath==='out/extension.js')!,operation=model.nodes.find(n=>n.attributes.dictionaryStackId==='esbuild'&&n.architecture?.kind==='tool-operation');expect(operation).toBeDefined();expect(model.edges.some(e=>e.source===operation!.id&&e.target===output.id&&e.kind==='flow-generates')).toBe(true);expect(model.edges.some(e=>e.source===output.id&&e.kind==='flow-loads')).toBe(true);
});
it('uses command working directory rather than build-file directory',async()=>{const {model}=await scan({'package.json':JSON.stringify({name:'cwd',scripts:{build:'cd nested && node ../tools/build.mjs'},devDependencies:{esbuild:'0.25'}}),'tools/build.mjs':"import{build}from'esbuild';build({entryPoints:['index.ts'],outfile:'out.js'})",'nested/index.ts':'export const x=1;'});expect(model.nodes.some(n=>n.attributes.artifactPath==='nested/out.js')).toBe(true);expect(model.nodes.some(n=>n.attributes.artifactPath==='tools/out.js')).toBe(false);});
it.each(["function unused(){build({entryPoints:['in.ts'],outfile:'out.js'})}","if(process.env.RUN){build({entryPoints:['in.ts'],outfile:'out.js'})}","context({entryPoints:['in.ts'],outfile:'out.js'})"])('does not promote unreachable or dynamic build invocation: %s',async body=>{const {model}=await scan({'package.json':JSON.stringify({scripts:{build:'node tools/build.mjs'},devDependencies:{esbuild:'0.25'}}),'tools/build.mjs':"import{build,context}from'esbuild';"+body,'in.ts':'export const x=1;'});expect(model.edges.some(e=>e.kind==='flow-generates')).toBe(false);});
it('keeps package, manifest loading and explicit publishing distinct',async()=>{
 const {model,input}=await scan({'package.json':JSON.stringify({name:'addon',version:'1.2.3',publisher:'author',engines:{vscode:'^1'},main:'out/addon.js',scripts:{build:'esbuild in.ts --outfile=out/addon.js',package:'vsce package --out packages/',publish:'vsce publish'}}),'.vscodeignore':'**\n!out/addon.js\n','in.ts':'export const x=1;','.vscode/launch.json':JSON.stringify({configurations:[{type:'extensionHost',request:'launch',args:['--extensionDevelopmentPath=${workspaceFolder}']}]})});
 expect(input.sources['.vscodeignore']).toBeDefined();const packaging=model.nodes.find(n=>n.attributes.purpose==='package')!;expect(packaging).toBeDefined();expect(model.nodes.some(n=>n.attributes.artifactPath==='packages/addon-1.2.3.vsix')).toBe(true);expect(model.edges.some(e=>e.target===packaging.id&&model.nodes.find(n=>n.id===e.source)?.attributes.artifactPath==='out/addon.js')).toBe(true);expect(model.edges.filter(e=>e.kind==='flow-loads')).toHaveLength(2);expect(model.edges.filter(e=>e.kind==='flow-deploys')).toHaveLength(1);
});
it('does not infer publishing from vscode:prepublish or manifest publisher',async()=>{const {model}=await scan({'package.json':JSON.stringify({name:'addon',version:'1.0.0',publisher:'author',engines:{vscode:'^1'},main:'out/main.js',scripts:{'vscode:prepublish':'node nothing.js',package:'vsce package'}}),'nothing.js':'console.log("fixture")'});expect(model.edges.some(e=>e.kind==='flow-deploys')).toBe(false);expect(model.nodes.some(n=>n.attributes.purpose==='package')).toBe(true);});
it('lays out operation-free sources beside contained service sets, keeping cycles and isolated subjects',()=>{
 const n=(id:string,stage:string):SemanticNode=>({id,label:id,kind:'subsystem',group:'test',confidence:'source',evidence:[],attributes:{simpleStage:stage,simpleOverview:true}});
 const nodes=[n('origin','source'),n('isolated','source'),...Array.from({length:8},(_,i)=>n('target'+i,'arrival'))],edges=nodes.slice(2).map(n=>({id:n.id,source:'origin',target:n.id,kind:'service-use',label:'uses',confidence:'source' as const,evidence:[],views:['architecture-map' as const]}));edges.push({...edges[0]!,id:'reverse',source:'target0',target:'origin'});const graph:SemanticGraph={view:'architecture-map',nodes,edges},before=JSON.stringify(edges),p=layoutSimpleArchitecture(graph).positions2d;
 expect(p.size).toBe(10);expect(p.get('origin')!.x).toBe(0);expect(p.get('origin')!.y).toBeLessThanOrEqual(Math.min(...nodes.slice(2).map(n=>p.get(n.id)!.y)));expect(new Set(nodes.slice(2).map(n=>p.get(n.id)!.x)).size).toBeGreaterThan(1);expect(JSON.stringify(edges)).toBe(before);
});

it('joins two explicitly included outputs into one VSIX without treating a sibling package as included',async()=>{
 const {model}=await scan({'package.json':JSON.stringify({name:'addon',version:'2.0.0',engines:{vscode:'^1'},main:'dist/extension.js',scripts:{extension:'esbuild main.ts --outfile=dist/extension.js',browser:'esbuild ui.ts --outfile=dist/web/assets/app.js',unrelated:'esbuild other.ts --outfile=other/output.js',package:'vsce package'}}),'.vscodeignore':'**\n!dist/extension.js\n!dist/web/assets/*.js\n','main.ts':'export function activate(){}','ui.ts':'export const x=1','other.ts':'export const y=2'});
 const op=model.nodes.find(n=>n.attributes.purpose==='package')!,inputs=model.edges.filter(e=>e.target===op.id&&e.kind==='flow-input').map(e=>model.nodes.find(n=>n.id===e.source)?.attributes.artifactPath).filter(Boolean);
 expect(inputs).toEqual(expect.arrayContaining(['dist/extension.js','dist/web/assets/app.js']));expect(inputs).not.toContain('other/output.js');
});
it.each(['cd elsewhere; next build','cd $UNKNOWN && next build','cd elsewhere && echo ok; next build'])('keeps ambiguous working directory unresolved: %s',async command=>{const {model}=await scan(nextSources({build:command}));expect(model.edges.some(e=>e.kind==='flow-generates')).toBe(false);});
it('keeps similar Firebase endpoints separate without a confirmed project and explains why',async()=>{
 const {model}=await scan({'package.json':JSON.stringify({name:'sample',dependencies:{firebase:'12'}}),'firebase.json':'{"emulators":{"auth":{"port":9099},"firestore":{"port":8080}}}', '.firebaserc':'{"projects":{"default":"configured-project"}}','src/client.ts':"import{initializeApp}from'firebase/app';import{getAuth,connectAuthEmulator}from'firebase/auth';const app=initializeApp({projectId:process.env.PROJECT});const auth=getAuth(app);connectAuthEmulator(auth,'http://127.0.0.1:9099');"});
 const nodes=model.nodes.filter(n=>n.attributes.dictionaryStackId==='firebase-authentication'&&n.attributes.environment==='local');expect(nodes).toHaveLength(2);expect(nodes.map(n=>n.attributes.providerOriginLabel)).toEqual(expect.arrayContaining(['設定で定義','コード側の接続設定']));expect(nodes.some(n=>String(n.attributes.providerIdentityNote).includes('静的に未特定'))).toBe(true);
});

it('does not assume working directory hidden in an unknown build-options spread',async()=>{const {model}=await scan({'package.json':JSON.stringify({scripts:{build:'node build.mjs'},devDependencies:{esbuild:'0.25'}}),'build.mjs':"import{build}from'esbuild';build({...unknown,entryPoints:['in.ts'],outfile:'out.js'})",'in.ts':'export const x=1;'});expect(model.edges.some(e=>e.kind==='flow-generates')).toBe(false);});
it('recognizes a proven same-project Firebase endpoint while preserving both evidence locations',async()=>{
 const {model}=await scan({'package.json':JSON.stringify({name:'sample',dependencies:{firebase:'12'}}),'firebase.json':'{"emulators":{"auth":{"port":9099}}}', '.firebaserc':'{"projects":{"default":"project-a"}}','src/client.ts':"import{initializeApp}from'firebase/app';import{getAuth,connectAuthEmulator}from'firebase/auth';const app=initializeApp({projectId:'project-a'});const auth=getAuth(app);connectAuthEmulator(auth,'http://127.0.0.1:9099');"});const nodes=model.nodes.filter(n=>n.attributes.dictionaryStackId==='firebase-authentication'&&n.attributes.environment==='local');expect(nodes).toHaveLength(1);expect(nodes[0]!.attributes.providerOriginLabel).toBe('設定・コードの対応確認');expect(new Set(nodes[0]!.evidence.map(e=>e.path))).toEqual(new Set(['firebase.json','src/client.ts']));
});

it('uses a code package as a readable origin even without any operation script',async()=>{
 const {model}=await scan({'package.json':JSON.stringify({name:'plain-code',dependencies:{firebase:'12'}}),'client.ts':"import{initializeApp}from'firebase/app';import{getAuth}from'firebase/auth';const app=initializeApp({projectId:'read-only'});const auth=getAuth(app);"});const simple=architectureSimpleOverview(prepareArchitectureScope(model));expect(simple.graph.nodes.find(n=>n.label==='plain-code')?.attributes.simpleStage).toBe('source');expect(model.nodes.some(n=>n.architecture?.kind==='tool-operation')).toBe(false);
});

it.skipIf(!process.env.GENERALITY_FIXTURE)('exports the independent operation-free source fixture for browser verification',async()=>{
 const {model,store}=await scan({'package.json':JSON.stringify({name:'no-operations',dependencies:{firebase:'12'}}),'firebase.json':'{"emulators":{"auth":{"port":9099},"firestore":{"port":8080},"storage":{"port":9199}}}', '.firebaserc':'{"projects":{"default":"fixture"}}','src/client.ts':"import{initializeApp}from'firebase/app';import{getAuth,connectAuthEmulator}from'firebase/auth';const app=initializeApp({projectId:process.env.PROJECT});const auth=getAuth(app);connectAuthEmulator(auth,'http://127.0.0.1:9099');"});
 expect(model.nodes.some(n=>n.architecture?.kind==='tool-operation')).toBe(false);writeFileSync('.cache/generality/no-operations.after.model.json',JSON.stringify(model));writeFileSync('.cache/generality/no-operations.after.store.json',JSON.stringify(store));
});

it('keeps separate esbuild CLI outputs attached to their actual command fragment',async()=>{
 const {model}=await scan({'package.json':JSON.stringify({scripts:{build:'esbuild one.ts --outfile=one.js && esbuild two.ts --outfile=two.js'},devDependencies:{esbuild:'0.25'}}),'one.ts':'export const one=1','two.ts':'export const two=2'});
 for(const output of ['one.js','two.js']){const target=model.nodes.find(n=>n.attributes.artifactPath===output)!;const incoming=model.edges.filter(e=>e.target===target.id&&e.kind==='flow-generates');expect(incoming).toHaveLength(1);expect(model.nodes.find(n=>n.id===incoming[0]!.source)?.attributes.command).toContain('--outfile='+output);}
});
it('does not map a missing Next directory to the parent application',async()=>{const {model}=await scan(nextSources({build:'next build absent'}));expect(model.edges.some(e=>e.kind==='flow-input'||e.kind==='flow-generates')).toBe(false);});

it.each(["let options={entryPoints:['in.ts'],outfile:'out.js'};build(options)","const options={entryPoints:['in.ts'],outfile:'out.js'};options.outfile=process.env.OUT;build(options)"])('retains unresolved mutated build settings without guessing their outputs: %s',async body=>{const {model}=await scan({'package.json':JSON.stringify({scripts:{build:'node build.mjs'},devDependencies:{esbuild:'0.25'}}),'build.mjs':"import{build}from'esbuild';"+body,'in.ts':'export const x=1;'});expect(model.edges.some(e=>e.kind==='flow-generates')).toBe(false);});
