// @vitest-environment node
import {expect,it} from 'vitest';
import {readFileSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {architectureSimpleOverview} from './architectureSimple';
import {prepareArchitectureScope} from './architectureProjection';
import {simpleArgumentLabel,simpleResourceEndpoints} from './architectureSimpleAnnotations';
import type {SemanticGraph,SemanticNode,SemanticEdge} from './types';
const node=(id:string,kind:NonNullable<SemanticNode['architecture']>['kind']='application'):SemanticNode=>({id,label:id,kind:'subsystem',group:'fixture',confidence:'source',attributes:{},evidence:[],architecture:{kind,entryPaths:[],roles:[],environments:[],context:[],memberIds:[],files:[],technologyNames:[],auxiliary:false}});
const edge=(id:string,source:string,target:string,kind='flow-input'):SemanticEdge=>({id,source,target,kind,label:kind,confidence:'source',evidence:[],views:['architecture-map']});
const tool=(id:string,purpose:string):SemanticNode=>({...node(id,'tool-operation'),label:'Tool',attributes:{purpose,dictionaryStackId:'generic',configurationPath:'fixture.config'}});
it.each(['review-east','任意の環境'])('places the entire recorded feeder next to the shared publication in %s',environment=>{
 const a=node('a'),b=node('b'),build=tool('build','build'),serve=tool('serve','serve'),publish=tool('publish','deploy'),artifact=node('artifact','artifact'),arrival=node('arrival','execution-config'),dev=node('dev','execution-config');publish.architecture!.environments=[environment];
 const model:SemanticGraph={view:'architecture-map',nodes:[a,b,build,serve,publish,artifact,arrival,dev],edges:[edge('a','a','publish'),edge('b','b','build'),edge('gen','build','artifact','flow-generates'),edge('use','artifact','publish'),edge('pub','publish','arrival','flow-deploys'),edge('serve','b','serve'),edge('dev','serve','dev','flow-starts')]};
 const before=JSON.stringify(model),simple=architectureSimpleOverview(prepareArchitectureScope(model)),p=(id:string)=>simple.graph.architectureView!.positions2d!.get(simple.owners.get(id)!)!;
 expect(p('build').y).toBe(p('publish').y);expect(p('arrival').y).toBe(p('publish').y);expect(p('serve').y).not.toBe(p('publish').y);expect(simple.graph.nodes.filter(n=>n.id===simple.owners.get('publish'))).toHaveLength(1);expect(simple.graph.nodes.find(n=>n.id===simple.owners.get('publish'))!.attributes.simpleSourceIds).toHaveLength(2);expect(JSON.stringify(model)).toBe(before);
});
it('moves folded start-script references to annotations but keeps preconditions and original records',()=>{
 const owner=node('package','code-package'),app=node('app'),script=tool('script','script'),start=tool('start','start'),apply=tool('apply','apply'),runtime=node('runtime','execution-config');script.attributes.definitionOwnerId=owner.id;
 const model:SemanticGraph={view:'architecture-map',nodes:[owner,app,script,start,apply,runtime],edges:[edge('call-a','script','start','flow-invokes'),edge('call-b','script','apply','flow-invokes'),edge('input','app','start'),edge('starts','start','runtime','flow-starts'),{...edge('order','apply','start','flow-precedes'),details:{conditional:true}}]};
 const simple=architectureSimpleOverview(prepareArchitectureScope(model));expect(simple.referenceEdges).toHaveLength(2);expect(simple.graph.edges.some(e=>e.kind==='flow-invokes')).toBe(false);expect(simple.graph.edges.some(e=>e.kind==='flow-precedes'&&e.details?.conditional)).toBe(true);expect(new Set([...simple.relations.values()].flatMap(r=>r.edgeIds))).toEqual(new Set(model.edges.map(e=>e.id)));expect(simple.graph.nodes.find(n=>n.id===simple.owners.get('start'))!.attributes.simpleReferenceCount).toBe(1);
});
it('keeps a standalone script as a visible starting point',()=>{
 const script=tool('script','script'),a=tool('a','start'),b=tool('b','deploy');const simple=architectureSimpleOverview(prepareArchitectureScope({view:'architecture-map',nodes:[script,a,b],edges:[edge('a','script','a','flow-invokes'),edge('b','script','b','flow-invokes')]}));expect(simple.referenceEdges).toHaveLength(0);expect(simple.graph.edges).toHaveLength(2);
});
it('places shared code near its users without cloning it or changing edge direction',()=>{
 const app=node('app'),lib=node('lib','shared-code'),op=tool('op','deploy'),runtime=node('runtime','execution-config'),simple=architectureSimpleOverview(prepareArchitectureScope({view:'architecture-map',nodes:[app,lib,op,runtime],edges:[edge('use','app','lib','code-reference'),edge('in','app','op'),edge('out','op','runtime','flow-deploys')]}));const pos=simple.graph.architectureView!.positions2d!,a=pos.get(simple.owners.get('app')!)!,b=pos.get(simple.owners.get('lib')!)!;expect(Math.abs(a.x-b.x)).toBe(350);expect(Math.abs(a.y-b.y)).toBeLessThan(200);expect(simple.graph.edges.find(e=>e.kind==='simple-reference')?.target).toBe(simple.owners.get('lib'));expect(simple.graph.nodes.filter(n=>n.id===simple.owners.get('lib'))).toHaveLength(1);
});
const resource=(id:string,environment:string,place='cloud')=>{const n=node(id,'resource');n.label='DB';n.attributes.executionPlace=place;n.architecture!.environments=[environment];n.architecture!.identity={status:'unconfirmed',type:'SQL',reason:'configured',configurations:[{id:`setting-${id}`,path:'settings.json',binding:'DATA',environment,evidence:[{path:'settings.json',line:1,endLine:1,start:0,end:2,description:'binding'}]}]};return n;};
it('maps selected resource edges to exact original endpoints, including a multi-target line',()=>{
 const a=resource('a','custom','local'),b=resource('b','custom','cloud'),c=resource('c','release'),op=tool('apply','apply'),model:SemanticGraph={view:'architecture-map',nodes:[a,b,c,op],edges:[edge('a','apply','a','flow-applies'),edge('b','apply','b','flow-applies')]},simple=architectureSimpleOverview(prepareArchitectureScope(model));
 const match=simpleResourceEndpoints(simple,simple.graph.edges[0]!);expect(match).toHaveLength(1);expect(match[0]!.members.map(n=>n.id).sort()).toEqual(['a','b']);expect(match[0]!.labels.join(' ')).toContain('local');expect(match[0]!.labels.join(' ')).toContain('cloud');expect(match[0]!.members.some(n=>n.id==='c')).toBe(false);expect(simple.units.get(match[0]!.node.id)!.members).toHaveLength(3);
});
it('does not map an unresolved connection to an arbitrary resource member',()=>{
 const a=resource('a','custom'),b=resource('b','release'),unknown=node('unknown','unresolved'),op=tool('op','apply'),simple=architectureSimpleOverview(prepareArchitectureScope({view:'architecture-map',nodes:[a,b,unknown,op],edges:[edge('unknown','op','unknown','flow-applies')]}));expect(simpleResourceEndpoints(simple,simple.graph.edges[0]!)).toEqual([]);
});
it('uses the distinguishing flag while retaining complete arguments on the source',()=>{
 const a=tool('a','serve'),b=tool('b','serve'),c=tool('c','serve');a.attributes.usageArguments='--host localhost --mode alpha';b.attributes.usageArguments='--host localhost --mode beta';c.attributes.usageArguments='';expect(simpleArgumentLabel(a,[a,b])).toBe('mode=alpha');expect(simpleArgumentLabel(a,[a,c])).toBe('host指定あり');expect(simpleArgumentLabel(c,[a,c])).toBe('追加引数なし');expect(a.attributes.usageArguments).toContain('--host localhost');
 b.attributes.usageArguments='--host 0.0.0.0 --mode alpha';expect(simpleArgumentLabel(a,[a,b])).toBe('host=localhost');
});
it.skipIf(!process.env.SHARED_PUBLICATION)('conserves three saved inputs including annotations and compares with baseline',async()=>{
 const oldProjection=await import(/* @vite-ignore */ resolve('.cache/shared-publication/baseline-src/src/analyzer/semantic/architectureProjection.ts')),oldSimple=await import(/* @vite-ignore */ resolve('.cache/shared-publication/baseline-src/src/analyzer/semantic/architectureSimple.ts')),reports=[];
 for(const project of ['vehicle-management','git-lines','web-atlas']){const model:SemanticGraph=JSON.parse(readFileSync(`.cache/simple-polish/${project}.model.json`,'utf8')),before=JSON.stringify(model),base=prepareArchitectureScope(model,undefined,'',true),start=performance.now(),simple=architectureSimpleOverview(base),coldMs=performance.now()-start;expect(JSON.stringify(model)).toBe(before);expect([...simple.owners.keys()].sort()).toEqual(base.allowed.map(n=>n.id).sort());expect([...new Set([...simple.units.values()].flatMap(u=>u.internalEdges).concat([...simple.relations.values()].flatMap(r=>r.edgeIds)))].sort()).toEqual(model.edges.map(e=>e.id).sort());const oldBase=oldProjection.prepareArchitectureScope(model,undefined,'',true),t=performance.now(),old=oldSimple.architectureSimpleOverview(oldBase),oldMs=performance.now()-t,warm=performance.now();for(let i=0;i<100;i++)expect(architectureSimpleOverview(base)).toBe(simple);const warm100Ms=performance.now()-warm;
 reports.push({project,coldMs,oldMs,warm100Ms,nodes:simple.graph.nodes.length,beforeNodes:old.graph.nodes.length,lines:simple.graph.edges.length,beforeLines:old.graph.edges.length,references:simple.referenceEdges?.length,referenceRecords:new Set(simple.referenceEdges?.flatMap(e=>simple.relations.get(e.id)?.edgeIds??[])).size,display:simple.graph.nodes.map(n=>({id:n.id,label:n.label,stage:n.attributes.simpleStage,position:simple.graph.architectureView!.positions2d!.get(n.id)}))});}
 writeFileSync('.cache/shared-publication/results.json',JSON.stringify(reports,null,2));
},120000);
