// @vitest-environment node
import {expect,it} from 'vitest';
import {readFileSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {architectureSimpleOverview} from './architectureSimple';
import {prepareArchitectureScope} from './architectureProjection';
import {simpleResourceEndpoints} from './architectureSimpleAnnotations';
import type {SemanticGraph,SemanticNode,SemanticEdge} from './types';
const node=(id:string,kind:NonNullable<SemanticNode['architecture']>['kind']='application'):SemanticNode=>({id,label:id,kind:'subsystem',group:'fixture',confidence:'source',attributes:{},evidence:[],architecture:{kind,entryPaths:[],roles:[],environments:[],context:[],memberIds:[],files:[],technologyNames:[],auxiliary:false}});
const evidence=[{path:'renamable/settings.json',line:3,endLine:3,start:12,end:30,description:'recorded setting'}];
const edge=(id:string,source:string,target:string,kind:string):SemanticEdge=>({id,source,target,kind,label:'same label',confidence:'source',evidence,views:['architecture-map'],details:{architectureOrigin:'architecture',structural:true}});
it.each(['alpha','名称を変更したもの'])('annotates only verified correspondence and retains transport and preconditions: %s',prefix=>{
 const app=node(prefix),code=node(`${prefix}-code`,'code-definition'),runtime=node(`${prefix}-runtime`,'execution-config'),op=node('op','tool-operation'),other=node('other');code.attributes.logicalOwnerId=app.id;runtime.attributes.logicalOwnerId=app.id;op.attributes.purpose='serve';runtime.architecture!.environments=['任意環境'];
 const graph:SemanticGraph={view:'architecture-map',nodes:[app,code,runtime,op,other],edges:[edge('definition',app.id,runtime.id,'flow-definition'),edge('configures',code.id,runtime.id,'flow-configures'),edge('serves',runtime.id,app.id,'flow-serves'),edge('input',code.id,op.id,'flow-input'),edge('starts',op.id,runtime.id,'flow-starts'),edge('http',app.id,runtime.id,'http-request'),{...edge('order',other.id,op.id,'flow-precedes'),details:{conditional:true}},edge('other-served',runtime.id,other.id,'flow-serves')]};
 const before=JSON.stringify(graph),simple=architectureSimpleOverview(prepareArchitectureScope(graph));expect(simple.referenceEdges?.map(e=>e.kind).sort()).toEqual(['flow-configures','flow-definition','flow-serves']);expect(simple.graph.edges.map(e=>e.kind).sort()).toEqual(['flow-input','flow-precedes','flow-serves','flow-starts','http-request']);expect(new Set([...simple.relations.values()].flatMap(r=>r.edgeIds))).toEqual(new Set(graph.edges.map(e=>e.id)));expect(JSON.stringify(graph)).toBe(before);const target=simple.graph.nodes.find(n=>n.id===simple.owners.get(runtime.id))!;expect(target.attributes.simpleCorrespondenceSummary).toContain(`配信対象：${prefix}`);expect(target.attributes.simpleReferenceLabel).toContain('原本対応 3関係');
});
it('does not hide mixed provenance or unsupported structural meaning despite the same endpoints',()=>{
 const app=node('app'),runtime=node('runtime','execution-config');runtime.attributes.logicalOwnerId='app';const mixed={...edge('mixed','app','runtime','flow-definition'),provenance:{edges:[edge('real-http','app','runtime','http-request')]}},unknown={...edge('unknown','app','runtime','flow-configures'),details:{structural:false}};
 const simple=architectureSimpleOverview(prepareArchitectureScope({view:'architecture-map',nodes:[app,runtime],edges:[mixed,unknown]}));expect(simple.referenceEdges).toHaveLength(0);expect(simple.graph.edges).toHaveLength(2);
});
it('retains correspondence even without a startup route, without inventing an operation',()=>{
 const app=node('app'),runtime=node('runtime','execution-config');runtime.attributes.logicalOwnerId='app';const simple=architectureSimpleOverview(prepareArchitectureScope({view:'architecture-map',nodes:[app,runtime],edges:[edge('corresponds','app','runtime','flow-definition')]}));expect(simple.graph.nodes).toHaveLength(2);expect(simple.graph.edges).toHaveLength(0);expect(simple.referenceEdges).toHaveLength(1);expect(simple.relations.size).toBe(1);
});
it('places shared libraries after no-route users are known, ignoring repeated auxiliary votes',()=>{
 const a=node('client-a'),b=node('client-b'),lib=node('library','shared-code'),main=node('main'),tool=node('tool','tool-operation'),runtime=node('runtime','execution-config'),tests=Array.from({length:12},(_,i)=>{const n=node(`test-${i}`);n.architecture!.auxiliary=true;return n;});tool.attributes.purpose='start';
 const graph:SemanticGraph={view:'architecture-map',nodes:[main,tool,runtime,a,b,lib,...tests],edges:[edge('in',main.id,tool.id,'flow-input'),edge('out',tool.id,runtime.id,'flow-starts'),edge('a',a.id,lib.id,'code-reference'),edge('b',b.id,lib.id,'declaration-dependency'),...tests.map(n=>edge(n.id,n.id,lib.id,'code-reference'))]},base=prepareArchitectureScope(graph),simple=architectureSimpleOverview(base),p=(id:string)=>simple.graph.architectureView!.positions2d!.get(simple.owners.get(id)!)!;
 expect(p(lib.id).x).toBeLessThan(350);expect(Math.abs(p(lib.id).y-p(a.id).y)).toBeLessThanOrEqual(280);expect(simple.graph.nodes.filter(n=>n.id===simple.owners.get(lib.id))).toHaveLength(1);expect(simple.graph.edges.some(e=>e.source===simple.owners.get(a.id)&&e.target===simple.owners.get(lib.id))).toBe(true);expect(architectureSimpleOverview(base)).toBe(simple);
});
it('keeps a shared library with its own build route in that route band',()=>{
 const app=node('app'),lib=node('library','shared-code'),build=node('build','tool-operation'),artifact=node('artifact','artifact');build.attributes.purpose='build';const simple=architectureSimpleOverview(prepareArchitectureScope({view:'architecture-map',nodes:[app,lib,build,artifact],edges:[edge('ref','app','library','code-reference'),edge('in','library','build','flow-input'),edge('out','build','artifact','flow-generates')]}));expect(simple.graph.nodes.find(n=>n.id===simple.owners.get('library'))!.attributes.simplePlacement).toBe('route');
});
it('keeps an unspecified environment separate on a partially identified multi-target resource line',()=>{
 const make=(id:string,environment:string)=>{const n=node(id,'resource');n.architecture!.environments=environment?[environment]:[];n.architecture!.identity={status:'unconfirmed',type:'SQL',reason:'configured role only',configurations:[{id,path:'settings.json',binding:'DATA',environment,evidence}]};return n;},known=make('known','review'),unknown=make('unknown-environment',''),other=make('other','release'),op=node('op','tool-operation');op.attributes.purpose='apply';
 const simple=architectureSimpleOverview(prepareArchitectureScope({view:'architecture-map',nodes:[known,unknown,other,op],edges:[edge('known','op','known','flow-applies'),edge('partial','op','unknown-environment','flow-applies')]})),match=simpleResourceEndpoints(simple,simple.graph.edges[0]!)!;
 expect(match[0]!.members.map(n=>n.id).sort()).toEqual(['known','unknown-environment']);expect(match[0]!.labels.some(label=>label.includes('環境未特定'))).toBe(true);expect(match[0]!.labels.some(label=>label.includes('release'))).toBe(false);
});
it('does not assign the unresolved part of an operation to a known member of a resource collection',()=>{
 const make=(id:string,environment:string)=>{const n=node(id,'resource');n.architecture!.environments=[environment];n.architecture!.identity={status:'unconfirmed',type:'SQL',reason:'config',configurations:[{id,path:'settings.json',binding:'DATA',environment,evidence}]};return n;},known=make('known','review'),other=make('other','release'),unknown=node('unresolved','unresolved'),op=node('op','tool-operation');op.attributes.purpose='apply';
 const simple=architectureSimpleOverview(prepareArchitectureScope({view:'architecture-map',nodes:[known,other,unknown,op],edges:[edge('confirmed','op','known','flow-applies'),edge('unknown','op','unresolved','flow-applies')]}));
 for(const e of simple.graph.edges){const matches=simpleResourceEndpoints(simple,e),ids=simple.relations.get(e.id)!.edgeIds;if(ids.includes('unknown'))expect(matches).toEqual([]);else expect(matches.flatMap(m=>m.members.map(n=>n.id))).toEqual(['known']);}
});
it.skipIf(!process.env.CORRESPONDENCE)('compares three inputs, preserves main route coordinates and audits every resource endpoint',async()=>{
 const oldProjection=await import(/* @vite-ignore */ resolve('.cache/correspondence/baseline-src/src/analyzer/semantic/architectureProjection.ts')),oldSimple=await import(/* @vite-ignore */ resolve('.cache/correspondence/baseline-src/src/analyzer/semantic/architectureSimple.ts')),reports=[];
 for(const project of ['vehicle-management','git-lines','web-atlas']){const model:SemanticGraph=JSON.parse(readFileSync(`.cache/simple-polish/${project}.model.json`,'utf8')),before=JSON.stringify(model),base=prepareArchitectureScope(model,undefined,'',true),t=performance.now(),simple=architectureSimpleOverview(base),coldMs=performance.now()-t,oldBase=oldProjection.prepareArchitectureScope(model,undefined,'',true),ot=performance.now(),old=oldSimple.architectureSimpleOverview(oldBase),oldMs=performance.now()-ot;
 expect(JSON.stringify(model)).toBe(before);expect([...simple.owners.keys()].sort()).toEqual(base.allowed.map(n=>n.id).sort());expect([...new Set([...simple.units.values()].flatMap(u=>u.internalEdges).concat([...simple.relations.values()].flatMap(r=>r.edgeIds)))].sort()).toEqual(model.edges.map(e=>e.id).sort());
 for(const n of simple.graph.nodes.filter(n=>['route','shared-route'].includes(String(n.attributes.simplePlacement))))expect(simple.graph.architectureView!.positions2d!.get(n.id)).toEqual(old.graph.architectureView!.positions2d!.get(n.id));
 const endpoints=simple.graph.edges.flatMap(e=>simpleResourceEndpoints(simple,e).map(match=>{const ids=simple.relations.get(e.id)!.edgeIds,raw=model.edges.filter(e=>ids.includes(e.id));expect(match.members.every(n=>raw.some(e=>e.source===n.id||e.target===n.id))).toBe(true);return {source:simple.graph.nodes.find(n=>n.id===e.source)?.label,kind:e.kind,labels:match.labels,memberIds:match.members.map(n=>n.id)};}));
 reports.push({project,nodes:simple.graph.nodes.length,beforeLines:old.graph.edges.length,lines:simple.graph.edges.length,beforeReferences:old.referenceEdges?.length,references:simple.referenceEdges?.length,referenceRecords:new Set(simple.referenceEdges?.flatMap(e=>simple.relations.get(e.id)?.edgeIds??[])).size,coldMs,oldMs,endpoints,shared:simple.graph.nodes.filter(n=>n.architecture?.kind==='shared-code').map(n=>({label:n.label,before:old.graph.architectureView!.positions2d!.get(n.id),after:simple.graph.architectureView!.positions2d!.get(n.id)}))});}
 writeFileSync('.cache/correspondence/results.json',JSON.stringify(reports,null,2));
},120000);
