// @vitest-environment node
import {beforeAll,describe,it,expect} from 'vitest';
import {scanProjectFiles} from '../scan';
import {semanticInput} from './client';
import {analyzeSemanticSources} from './analyze';
import {initializeTestParser,testLanguage,testParser} from './testRuntime';
import {projectSemanticView} from './project';
import {frameworkCoverageFixtures} from '../fixtures/stack-coverage/frameworks';
import {providerCoverageFixtures} from '../fixtures/stack-coverage/providers';
import {commandSourceRange,parseCommandExpression} from '../commandParser';
import completionFixtures from '../fixtures/stack-coverage/completion.json';
beforeAll(initializeTestParser);
async function inspect(sources:Record<string,string>){const store=await scanProjectFiles(Object.entries(sources).map(([relativePath,source])=>({relativePath,name:relativePath.split('/').at(-1)!,extension:'.'+relativePath.split('.').at(-1),size:source.length,readText:async()=>source})));const analysis=await analyzeSemanticSources(semanticInput(store),testLanguage,undefined,testParser);return{store,analysis};}
const packageJson='{"name":"fixture"}';
describe('remaining declared primitives and original regressions',()=>{
 it('connects Apache VirtualHost and ProxyPass to the explicit origin',async()=>{const sources=providerCoverageFixtures.find(item=>item.stackId==='apache-http-server')!.sources;const{analysis}=await inspect(sources);expect(analysis.edges.some(edge=>edge.kind==='proxy-pass')).toBe(true);expect(analysis.nodes.some(node=>node.attributes.documentRoot==='/var/www/html')).toBe(true);expect(analysis.architecture?.edges.some(edge=>edge.kind==='proxy-pass')).toBe(true);});
 it.each([
  ['cloudflare-cdn','cdn.tf.json',JSON.stringify({resource:{cloudflare_ruleset:{cache:{name:'cache',zone_id:'zone',kind:'zone',phase:'http_request_cache_settings',rules:[{action:'set_cache_settings',expression:'http.host eq "assets.example"',action_parameters:{cache:true,edge_ttl:{mode:'override_origin',default:120}}}]}}}}),'set_cache_settings'],
  ['google-cloud-cdn','cdn.tf','resource "google_compute_backend_bucket" "assets" {\n name="assets"\n bucket_name="assets"\n enable_cdn=true\n cdn_policy {\n cache_mode="CACHE_ALL_STATIC"\n default_ttl=120\n }\n}','CACHE_ALL_STATIC'],
  ['amazon-cloudfront','cdn.json',JSON.stringify({Resources:{Assets:{Type:'AWS::CloudFront::Distribution',Properties:{DistributionConfig:{Enabled:true,DefaultCacheBehavior:{TargetOriginId:'assets',ViewerProtocolPolicy:'redirect-to-https',DefaultTTL:120},Origins:[{Id:'assets',DomainName:'origin.example'}]}}}}}),'redirect-to-https'],
  ['akamai-ion','property.json',JSON.stringify({productId:'prd_Fresca',propertyId:'prp_1',rules:{behaviors:[{name:'caching',options:{behavior:'MAX_AGE',ttl:'1d'}},{name:'origin',options:{hostname:'origin.example'}}]}}),'MAX_AGE'],
 ] as const)('%s preserves its declared cache/behavior form in the resulting resource',async(id,path,source,value)=>{const{store,analysis}=await inspect({'package.json':packageJson,[path]:source});const resource=store.facts.find(fact=>fact.kind==='resource'&&fact.dictionaryStackId===id&&!fact.metadata.originOnly)!;expect(resource.metadata.deliverySettings).toContain(value);expect(resource.metadata.observed).toBe(false);expect(analysis.nodes.some(node=>node.kind==='resource'&&node.attributes.deliverySettings===resource.metadata.deliverySettings)).toBe(true);});
 it('keeps original command slices for quoted YAML scalars',async()=>{const source='launch:\n  script: \'java Application.java && echo done\'\n';const{store}=await inspect({'.gitlab-ci.yml':source,'Application.java':'class Application{public static void main(String[] args){}}'});const script=store.facts.find(fact=>fact.kind==='package-script'&&fact.scriptName==='launch')!;if(script.kind!=='package-script')throw Error('script missing');expect(parseCommandExpression(script.command).map(fragment=>{const range=commandSourceRange(source,script,fragment);return source.slice(range.start,range.end);})).toEqual(['java Application.java','echo done']);});
 it.each(['amazon-cloudfront','akamai-ion'] as const)('%s transports the explicit origin through Runtime and Architecture',async id=>{const sources=providerCoverageFixtures.find(item=>item.stackId===id)!.sources;const{analysis}=await inspect(sources);expect(analysis.edges.some(edge=>edge.kind==='delivery-origin')).toBe(true);expect(analysis.architecture?.edges.some(edge=>edge.kind==='delivery-origin')).toBe(true);});
 it('does not join selector-less services, unknown ingress backends or namespace lookalikes',async()=>{const sources={'package.json':packageJson,'service.yaml':'apiVersion: v1\nkind: Service\nmetadata: {name: api, namespace: a}\nspec: {ports: [{port: 80}]}','ingress.yaml':'apiVersion: networking.k8s.io/v1\nkind: Ingress\nmetadata: {name: web, namespace: b}\nspec: {defaultBackend: {service: {name: api, port: {number: 80}}}}'};const{analysis,store}=await inspect(sources);expect(analysis.edges.some(edge=>['selects-workload','routes-to-service'].includes(edge.kind))).toBe(false);expect(store.warnings.some(warning=>warning.message.includes('Serviceは未解決'))).toBe(true);});
 it('leaves dynamic proxy targets unresolved and masks credentials in declared relation labels',async()=>{const{analysis}=await inspect({'package.json':packageJson,'nginx.conf':'server { location /dynamic { proxy_pass http://$upstream; } location /api { proxy_pass https://user:secret-marker@origin.example/api; } }'});expect(analysis.edges.filter(edge=>edge.kind==='proxy-pass')).toHaveLength(1);expect(JSON.stringify(analysis)).not.toContain('secret-marker');});
 it('does not treat a shadowed pytest namespace or model parameter as a fixture/model reference',async()=>{const{analysis}=await inspect({'pyproject.toml':'[project]\nname="app"\ndependencies=["pytest","django"]','test_app.py':'import pytest\ndef define(pytest):\n @pytest.fixture\n def item():\n  return 1\n return item\n','models.py':'from django.db import models\nclass User(models.Model):\n name=models.CharField(max_length=80)\ndef fake(User):\n return User.objects.filter(name="x")\n'});expect(analysis.nodes.some(node=>node.attributes.fixture)).toBe(false);expect(analysis.edges.some(edge=>edge.kind==='reads-model')).toBe(false);});
 it.each(['wpf-explicit-main','boot-ci'] as const)('%s connects the declared command to the real entry and application',async id=>{const{store,analysis}=await inspect(completionFixtures[id]);const runtime=store.facts.find(fact=>fact.kind==='runtime')!;expect(runtime).toBeDefined();const main=analysis.nodes.find(node=>node.kind==='function'&&node.attributes.name===(id==='boot-ci'?'main':'Main'))!;expect(main).toBeDefined();expect(analysis.edges.some(edge=>edge.kind==='runtime-entry'&&edge.target===main.id)).toBe(true);expect(analysis.architecture?.nodes.some(node=>node.architecture?.kind==='application'&&node.architecture.entryPaths.includes(main.path!))).toBe(true);expect(runtime.metadata.observed).toBe(false);});
 it.each(['clerk-middleware-handler','auth0-domain-handler'] as const)('%s keeps authentication handler, operation and response data',async id=>{const{analysis}=await inspect(completionFixtures[id]);const product=id.startsWith('clerk')?'clerk':'auth0';expect(analysis.nodes.some(node=>node.attributes.dictionaryStackId===product&&node.attributes.operation==='auth')).toBe(true);expect(projectSemanticView(analysis,'data-flow').nodes.some(node=>node.data?.role==='return')).toBe(true);if(product==='auth0')expect(analysis.nodes.some(node=>node.attributes.endpoint==='https://tenant.example.test')).toBe(true);else expect(analysis.edges.some(edge=>edge.kind==='handles'&&analysis.nodes.find(node=>node.id===edge.target)?.attributes.name==='profile')).toBe(true);});
 it.each(['netlify','firebase-hosting','apache-http-server'] as const)('%s retains its declared metadata and source scope',async id=>{const fixture=providerCoverageFixtures.find(item=>item.stackId===id)!;const{store,analysis}=await inspect(fixture.sources);const resource=store.facts.find(fact=>fact.kind==='resource'&&fact.dictionaryStackId===id)!;expect(resource).toBeDefined();expect(resource.metadata.observed).toBe(false);if(id==='netlify')expect(resource.metadata).toMatchObject({publish:'public',functions:'functions'});if(id==='firebase-hosting')expect(resource.metadata).toMatchObject({publicDirectory:'public',hostingTarget:'web'});if(id==='apache-http-server')expect(resource.metadata.directives).toContain('/api http://api:8000');expect(analysis.architecture?.nodes.some(node=>node.attributes.dictionaryStackId===id)).toBe(true);});
 it('connects Workers KV delete to its explicit binding',async()=>{const fixture=providerCoverageFixtures.find(item=>item.stackId==='cloudflare-kv')!;const{analysis}=await inspect({...fixture.sources,'worker.ts':fixture.sources['worker.ts']!.replace('return new Response','await env.CACHE.delete("old");return new Response')});const op=analysis.nodes.find(node=>node.kind==='operation'&&node.attributes.callee==='env.CACHE.delete')!;expect(op).toBeDefined();expect(analysis.edges.some(edge=>edge.source===op.id&&edge.kind==='uses-resource'&&analysis.nodes.find(node=>node.id===edge.target)?.attributes.binding==='CACHE')).toBe(true);});
 it('uses the canonical Axum routing method behind an alias',async()=>{const sources=frameworkCoverageFixtures.find(item=>item.stackId==='axum')!.sources;const{analysis}=await inspect(Object.fromEntries(Object.entries(sources).map(([path,source])=>[path,source.replace('routing::get,','routing::get as route_get,').replace('get(users)','route_get(users)')])));expect(analysis.nodes.filter(node=>node.kind==='entry'&&node.attributes.endpoint).map(node=>node.label)).toEqual(['GET /api/users']);});
 it('rejects unrelated ASP MapControllers receivers',async()=>{const sources=frameworkCoverageFixtures.find(item=>item.stackId==='aspnet-core')!.sources;const{analysis}=await inspect({...sources,'Program.cs':sources['Program.cs']!.replace('app.MapControllers();','var fake=new Fake();fake.MapControllers();')+'class Fake{public void MapControllers(){}}'});expect(analysis.nodes.some(node=>node.kind==='entry'&&node.attributes.routeRegistrationVerified)).toBe(false);});
 it('retains quoted Fastify schema keys and status-specific response names',async()=>{const{analysis}=await inspect({'app.ts':"import fastify from'fastify';const app=fastify();function handler(req,reply){return {name:req.body.name};}app.post('/users',{'schema':{'body':{'type':'object','properties':{'name':{'type':'string'}},'required':['name']},'response':{200:{type:'object',properties:{name:{type:'string'}}},400:{type:'object',properties:{error:{type:'string'}}}}}},handler);"});expect(analysis.edges.filter(edge=>edge.kind==='response-schema')).toHaveLength(2);expect(analysis.nodes.find(node=>node.label==='POST /users response 400')?.fields?.[0]?.name).toBe('error');expect(analysis.nodes.find(node=>node.label==='POST /users body')?.fields?.[0]).toMatchObject({name:'name',optional:false});});
 it('keeps each YAML sequence command original range',async()=>{const source='launch:\n  script:\n    - java --class-path "lib/*" Application.java\n    - echo done\n';const{store}=await inspect({'.gitlab-ci.yml':source,'Application.java':'class Application{public static void main(String[] args){}}'});const script=store.facts.find(fact=>fact.kind==='package-script'&&fact.scriptName==='launch')!;if(script.kind!=='package-script')throw Error('script missing');expect(parseCommandExpression(script.command).map(fragment=>{const range=commandSourceRange(source,script,fragment);return source.slice(range.start,range.end);})).toEqual(['java --class-path "lib/*" Application.java','echo done']);});
 it('connects pytest fixture requests while excluding ordinary functions and keeping tests opt-in',async()=>{const sources={'pyproject.toml':'[project]\nname="tests"\ndependencies=["pytest"]','test_app.py':'import pytest\n@pytest.fixture\ndef sample():\n return 2\ndef ordinary():\n return 3\ndef test_value(sample,ordinary):\n assert sample==2\n'};const{analysis}=await inspect(sources);const fixture=analysis.nodes.find(node=>node.attributes.fixture==='sample')!;expect(fixture).toBeDefined();expect(analysis.edges.filter(edge=>edge.kind==='requests-fixture').map(edge=>edge.target)).toEqual([fixture.id]);expect(projectSemanticView(analysis,'runtime-flow').nodes.filter(node=>node.attributes.fixture).every(node=>node.group==='Tests')).toBe(true);});
 it.each(['django','ruby-on-rails'])('connects %s explicit queries to the real model and result',async product=>{const base=frameworkCoverageFixtures.find(item=>item.stackId===product)!.sources;const sources=product==='django'?{...base,'urls.py':base['urls.py']!.replace("return {'name':'Alice'}","return User.objects.filter(name='Alice').first()")}: {...base,'app/controllers/users_controller.rb':base['app/controllers/users_controller.rb']!.replace("{name: 'Alice'}","User.where(name: 'Alice').first")};const{analysis}=await inspect(sources);expect(analysis.edges.some(edge=>edge.kind==='reads-model'&&analysis.nodes.find(node=>node.id===edge.target)?.label==='User')).toBe(true);expect(analysis.edges.some(edge=>edge.kind==='result-model')).toBe(true);expect(projectSemanticView(analysis,'data-flow').nodes.length).toBeGreaterThan(0);});
 it('retains Service selector and Ingress declarations across YAML documents without namespace crossover',async()=>{const deployment='apiVersion: apps/v1\nkind: Deployment\nmetadata: {name: api, namespace: app}\nspec:\n  template:\n    metadata: {labels: {app: api}}\n    spec: {containers: [{name: api, image: example/api:1}]}\n';const service='apiVersion: v1\nkind: Service\nmetadata: {name: api, namespace: app}\nspec: {selector: {app: api}, ports: [{port: 80, targetPort: 8080}]}\n';const ingress='apiVersion: networking.k8s.io/v1\nkind: Ingress\nmetadata: {name: web, namespace: app}\nspec:\n  rules:\n    - http:\n        paths:\n          - path: /\n            pathType: Prefix\n            backend: {service: {name: api, port: {number: 80}}}\n';const{analysis}=await inspect({'package.json':packageJson,'deploy.yaml':deployment+'---\n'+service+'---\n'+ingress,'other.yaml':deployment.replace('namespace: app','namespace: other')});expect(analysis.edges.filter(edge=>edge.kind==='selects-workload')).toHaveLength(1);expect(analysis.edges.filter(edge=>edge.kind==='routes-to-service')).toHaveLength(1);expect(analysis.architecture?.edges.some(edge=>edge.kind==='routes-to-service')).toBe(true);});
 it('connects NGINX server/location/upstream with original directives, excluding quoted data',async()=>{const source='http { upstream backend { server api:8000; } server { server_name app.example; set $text "proxy_pass http://fake"; location /api/ { proxy_pass http://backend/v1/; } } }';const{analysis}=await inspect({'package.json':packageJson,'nginx.conf':source});expect(analysis.edges.filter(edge=>edge.kind==='proxy-pass')).toHaveLength(1);expect(analysis.edges.some(edge=>edge.kind==='upstream-server')).toBe(true);expect(analysis.architecture?.edges.some(edge=>edge.kind==='declares-location')).toBe(true);expect(analysis.nodes.some(node=>node.label.includes('fake'))).toBe(false);});
 it('retains Pages upload artifact declaration and publication relation',async()=>{const fixture=providerCoverageFixtures.find(item=>item.stackId==='github-pages')!;const{store,analysis}=await inspect(fixture.sources);expect(store.facts.find(fact=>fact.kind==='resource'&&fact.metadata.artifactName)?.metadata.outputPath).toBe('public');expect(analysis.edges.some(edge=>edge.kind==='publishes-artifact')).toBe(true);expect(analysis.architecture?.edges.some(edge=>edge.kind==='publishes-artifact')).toBe(true);});
 it('keeps cache settings and Bunny hostname references as declarations',async()=>{const source='resource "fastly_service_vcl" "web" {\n name="web"\n default_ttl=60\n backend {\n name="origin"\n address="origin.example"\n }\n}\nresource "bunnynet_pullzone" "assets" {\n name="assets"\n cache_enabled=true\n origin {\n type="OriginUrl"\n url="https://origin.example"\n }\n}\nresource "bunnynet_pullzone_hostname" "domain" {\n pullzone=bunnynet_pullzone.assets.id\n name="cdn.example.com"\n}\n';const{store,analysis}=await inspect({'package.json':packageJson,'cdn.tf':source});const fastly=store.facts.find(fact=>fact.kind==='resource'&&fact.dictionaryStackId==='fastly-cdn'&&!fact.metadata.originOnly)!;expect(JSON.parse(String(fastly.metadata.deliverySettings))).toMatchObject({default_ttl:60});expect(analysis.edges.some(edge=>edge.kind==='cdn-domain')).toBe(true);});
});
