// @vitest-environment node
import { beforeAll, describe, expect, it } from 'vitest';
import { scanProjectFiles } from '../scan';
import { semanticInput } from './client';
import { analyzeSemanticSources } from './analyze';
import { initializeTestParser, testLanguage, testParser } from './testRuntime';
import { dataCoverageFixtures } from '../fixtures/stack-coverage/data';
import { projectSemanticView } from './project';
beforeAll(initializeTestParser);
async function analyze(sources:Record<string,string>){const store=await scanProjectFiles(Object.entries(sources).map(([relativePath,source])=>({relativePath,name:relativePath.split('/').at(-1)!,extension:'.'+relativePath.split('.').at(-1),size:source.length,readText:async()=>source})));return analyzeSemanticSources(semanticInput(store),testLanguage,undefined,testParser);}
describe('additional static D primitives',()=>{
  it('joins known Redux selectors and Pinia getter reads to their existing call/value flow',async()=>{for(const product of ['redux-toolkit','pinia']){const fixture=dataCoverageFixtures.find(item=>item.stackId===product)!;const analysis=await analyze(fixture.sources);if(product==='redux-toolkit'){expect(analysis.nodes.some(node=>node.kind==='external'&&node.label.includes('selectCount'))).toBe(false);expect(analysis.edges.some(edge=>edge.kind==='calls'&&analysis.nodes.find(node=>node.id===edge.target)?.attributes.name==='selectCount')).toBe(true);}else{const uses=analysis.nodes.filter(node=>node.data?.expression==='counter.double'&&node.data.role==='property-read');expect(uses).toHaveLength(1);expect(uses[0]!.kind).toBe('value');expect(analysis.edges.some(edge=>edge.kind==='selects-state'&&edge.source===uses[0]!.id)).toBe(true);expect(analysis.edges.some(edge=>edge.source===uses[0]!.id&&analysis.nodes.find(node=>node.id===edge.target)?.data?.role==='return')).toBe(true);}}});
  it('does not bind SQLAlchemy arguments and shadowed constructors to a module model',async()=>{const analysis=await analyze({'app.py':'from sqlalchemy import select\nfrom sqlalchemy.orm import DeclarativeBase, Mapped, Session\nclass Base(DeclarativeBase):\n pass\nclass User(Base):\n name: Mapped[str]\ndef fake(engine,User):\n session=Session(engine)\n item=User(name="fake")\n session.add(item)\n return select(User)\n'});expect(analysis.edges.some(edge=>['query-model','result-model','writes-model'].includes(edge.kind))).toBe(false);});
  it('keeps Pinia getter this within its own lexical function boundary',async()=>{const analysis=await analyze({'app.ts':"import{defineStore}from'pinia';const useCounter=defineStore('counter',{state:()=>({count:0}),getters:{double(){function other(){return this.count;}return 1;}}});const store=useCounter();function read(){return store.double;}"});expect(analysis.edges.some(edge=>edge.kind==='reads-state')).toBe(false);expect(analysis.edges.some(edge=>edge.kind==='selects-state')).toBe(true);});
  it.each(['modular','admin'])('does not erase dynamic segments in a %s Firestore document path',async mode=>{const source=mode==='modular'?"import{getFirestore,doc,getDoc}from'firebase/firestore';const db=getFirestore();async function read(id){return getDoc(doc(db,'users',id,'posts','first'));}":"import{getFirestore}from'firebase-admin/firestore';const db=getFirestore();async function read(id){return db.collection('users').doc(id).get();}";const analysis=await analyze({'app.ts':source});const references=analysis.nodes.filter(node=>node.kind==='operation'&&node.attributes.resourceKind==='document');expect(references.length).toBeGreaterThan(0);for(const reference of references){expect(reference.attributes.resourcePath).toBeUndefined();expect(reference.attributes.referenceResolution).toBe('unresolved');expect(reference.attributes.resourcePrefix).toBe('users');}});
  it('keeps Table/relationship declarations and explicit query/write/result models',async()=>{
    const fixture=dataCoverageFixtures.find(item=>item.stackId==='sqlalchemy')!;const analysis=await analyze(fixture.sources);const models=projectSemanticView(analysis,'data-model').nodes;
    expect(models.find(node=>node.label==='logs')).toMatchObject({attributes:{storageName:'logs'},fields:[{name:'id',key:'primary'}]});
    const user=models.find(node=>node.label==='User')!,team=models.find(node=>node.label==='Team')!;expect(user.fields!.find(field=>field.name==='team')?.referenceIds).toContain(team.id);
    expect(analysis.edges.some(edge=>edge.source===user.id&&edge.target===team.id&&edge.kind==='model-reference')).toBe(true);
    expect(analysis.edges.some(edge=>edge.kind==='writes-model'&&edge.target===user.id&&analysis.nodes.find(node=>node.id===edge.source)?.attributes.callee==='session.add')).toBe(true);
  });
  it('does not create a SQLAlchemy Table from a shadowed factory',async()=>{const analysis=await analyze({'app.py':'from sqlalchemy import Table, Column, Integer\ndef define(Table):\n users=Table("users",None,Column("id",Integer))\n return users\n'});expect(analysis.edges.some(edge=>edge.kind==='table-definition')).toBe(false);});
  it.each(['modular','admin'])('retains %s Firestore document paths and payload/return flow',async mode=>{
    const source=mode==='modular'?"import{initializeApp}from'firebase/app';import{getFirestore,collection,doc,setDoc,getDoc}from'firebase/firestore';const app=initializeApp({projectId:'documents'});const db=getFirestore(app);async function save(){const ref=doc(collection(db,'users'),'alice');await setDoc(ref,{name:'Alice'});return getDoc(ref);}":"import{initializeApp}from'firebase-admin/app';import{getFirestore}from'firebase-admin/firestore';const app=initializeApp({projectId:'documents'});const db=getFirestore(app);async function save(){const ref=db.collection('users').doc('alice');await ref.set({name:'Alice'});return ref.get();}";
    const analysis=await analyze({'app.ts':source});const read=analysis.nodes.find(node=>node.kind==='operation'&&node.attributes.callee===(mode==='modular'?'getDoc':'ref.get'))!;
    expect(read.attributes).toMatchObject({dictionaryStackId:'cloud-firestore',resourcePath:'users/alice',resourceKind:'document'});
    expect(analysis.edges.some(edge=>edge.source===read.id&&edge.kind==='uses-resource')).toBe(true);expect(projectSemanticView(analysis,'data-flow').nodes.some(node=>node.data?.role==='return')).toBe(true);
    expect(analysis.edges.some(edge=>edge.kind==='writes-data')).toBe(true);
  });
  it('distinguishes Supabase service selectors from a table called auth',async()=>{const analysis=await analyze({'app.ts':"import{createClient}from'@supabase/supabase-js';const client=createClient('https://sample.supabase.co','public');async function run(){await client.from('auth').select();await client.auth.getUser();const bucket=client.storage.from('files');return bucket.download('one.txt');}"});const operation=(callee:string)=>analysis.nodes.find(node=>node.kind==='operation'&&node.attributes.callee===callee)!;
    expect(operation("client.from('auth').select").attributes.operation).toBe('database');expect(operation('client.auth.getUser').attributes.operation).toBe('auth');expect(operation('bucket.download').attributes.operation).toBe('storage');
  });
});
