// @vitest-environment node
import{beforeAll,describe,expect,it}from'vitest';
import{scanProjectFiles}from'../scan';import{semanticInput}from'./client';import{analyzeSemanticSources}from'./analyze';import{initializeTestParser,testLanguage,testParser}from'./testRuntime';import{dataCoverageFixtures}from'../fixtures/stack-coverage/data';
beforeAll(initializeTestParser);
async function analyze(sources:Record<string,string>){const store=await scanProjectFiles(Object.entries(sources).map(([relativePath,source])=>({relativePath,name:relativePath.split('/').at(-1)!,extension:'.'+relativePath.split('.').at(-1),size:source.length,readText:async()=>source})));return analyzeSemanticSources(semanticInput(store),testLanguage,undefined,testParser);}
describe('D local binding and value provenance',()=>{
 it('keeps Pydantic method annotations out of declared and serialized fields',async()=>{const fixture=dataCoverageFixtures.find(item=>item.stackId==='pydantic')!;const analysis=await analyze(fixture.sources);for(const model of analysis.nodes.filter(node=>node.kind==='model'&&['User','User serialized'].includes(node.label)))expect(model.fields?.map(field=>field.name)).toEqual(['name']);});
 it('does not resolve Mongoose refs through another lexical registry',async()=>{const analysis=await analyze({'app.ts':"import mongoose from'mongoose';function hidden(){const team=new mongoose.Schema({title:String});const Team=mongoose.model('Team',team);}const schema=new mongoose.Schema({name:String,team:{type:mongoose.Schema.Types.ObjectId,ref:'Team'}});const User=mongoose.model('User',schema);"});expect(analysis.edges.some(edge=>edge.kind==='orm-relation')).toBe(false);});
 it('keeps a shadowed Sequelize class out of CRUD and associations',async()=>{const analysis=await analyze({'app.ts':"import{Model,DataTypes,Sequelize}from'sequelize';const db=new Sequelize('sqlite::memory:');class User extends Model{}User.init({name:DataTypes.STRING},{sequelize:db});function save(User){return User.create({name:'fake'});}"});expect(analysis.edges.some(edge=>edge.kind==='writes-model'||edge.kind==='result-model')).toBe(false);});

 it.each(['redux-toolkit','pinia'])('keeps %s selector/getter reads bound to the declared state',async product=>{const fixture=dataCoverageFixtures.find(item=>item.stackId===product)!;const source=fixture.sources['app.ts']!;const modified=product==='redux-toolkit'?source.replace('return state.count;','function nested(state){return state.count;} return 1;').replace('counter.selectors.selectCount(store.getState())','fake.selectors.selectCount(store.getState())'):source.replace('return state.count*2;','function nested(state){return state.count;} return 1;').replace('return counter.double;','return fake.double;');const analysis=await analyze({...fixture.sources,'app.ts':modified});expect(analysis.edges.some(edge=>edge.kind==='reads-state'||edge.kind==='selects-state')).toBe(false);expect(analysis.edges.some(edge=>edge.kind==='registers-selector')).toBe(true);});

  it('separates Pydantic validation/serialization and ignores a shadowed decorator',async()=>{const source="from pydantic import BaseModel, field_validator\ndef field_validator(name):\n return lambda fn:fn\nclass User(BaseModel):\n name:str\n @field_validator('name')\n def fake(value):\n  return value\ndef save(value):\n user=User.model_validate(value)\n return user.model_dump()\n";const analysis=await analyze({'app.py':source});expect(analysis.edges.some(edge=>edge.kind==='registers-validator'||edge.kind==='validates-with')).toBe(false);const output=analysis.nodes.find(node=>node.kind==='operation'&&node.attributes.callee==='user.model_dump')!;expect(output.attributes.operation).toBe('serialization');expect(analysis.edges.some(edge=>edge.kind==='serializes'&&edge.target===output.id)).toBe(true);expect(analysis.edges.some(edge=>edge.kind==='validates'&&edge.target===output.id)).toBe(false);});
  it.each(['mongoose','sequelize'])('keeps %s same-name function-local model declarations separate',async product=>{
    const imports=product==='mongoose'?"import mongoose from'mongoose';":"import{Sequelize}from'sequelize';const db=new Sequelize('sqlite::memory:');";const factory=(field:string)=>product==='mongoose'?`const schema=new mongoose.Schema({${field}:String});const User=mongoose.model('User',schema);`:`const User=db.define('User',{${field}:'TEXT'});`;const analysis=await analyze({'app.ts':`${imports}function alpha(){${factory('name')}return User.create({name:'a'});}function beta(){${factory('title')}return User.create({title:'b'});}`});const models=analysis.nodes.filter(node=>node.kind==='model'&&node.label==='User'&&node.attributes.dictionaryStackId===product);expect(models).toHaveLength(2);expect(models.map(node=>node.fields?.map(field=>field.name))).toEqual([['name'],['title']]);for(const relation of analysis.edges.filter(edge=>edge.kind==='writes-model')){const operation=analysis.nodes.find(node=>node.id===relation.source)!;const model=analysis.nodes.find(node=>node.id===relation.target)!;const field=model.fields![0]!.name;expect(operation.evidence.some(at=>analysis.nodes.find(node=>node.attributes.name===(field==='name'?'alpha':'beta'))?.evidence.some(owner=>at.start>=owner.start&&at.end<=owner.end))).toBe(true);}
  });
  it.each([['pydantic','from pydantic import BaseModel\nclass User(BaseModel):\n name:str\ndef save(User,value):\n return User.model_validate(value)'],['sqlalchemy','from sqlalchemy.orm import Session\ndef save(Session):\n session=Session(None)\n session.commit()']])('does not use a shadowed %s class/factory parameter',async(product,source)=>{const analysis=await analyze({'app.py':source,'pyproject.toml':`[project]\nname="app"\ndependencies=["${product}"]`});expect(analysis.nodes.some(node=>node.kind==='operation'&&node.attributes.dictionaryStackId===product)).toBe(false);});
  it('does not turn a Redis scalar value method into a Redis client operation',async()=>{const analysis=await analyze({'app.ts':"import{createClient}from'redis';const client=createClient({url:'redis://localhost:6379'});async function read(){const value:string|null=await client.get('name');return value?.toUpperCase();}"});expect(analysis.nodes.some(node=>node.kind==='operation'&&String(node.attributes.callee).includes('toUpperCase')&&node.attributes.dictionaryStackId)).toBe(false);});
  it('excludes a discarded auth result and an Auth0 constructor from Session mapping',async()=>{const analysis=await analyze({'app.ts':"import{auth}from'@clerk/nextjs/server';import{Auth0Client}from'@auth0/nextjs-auth0/server';interface AppSession{userId:string;}const client=new Auth0Client();async function ignored(){const session:AppSession={userId:(await auth(),'fixed')};return session;}async function used(){const data=await client.getSession();const session:AppSession={userId:data?.user.sub??''};return session;}"});const edges=analysis.edges.filter(edge=>edge.kind==='maps-to-shape');expect(edges).toHaveLength(1);expect(analysis.nodes.find(node=>node.id===edges[0]!.source)?.attributes.callee).toBe('client.getSession');});
  it.each(['redis','supabase','auth0'])('retains both %s project uses of one explicitly shared endpoint',async product=>{const fixture=dataCoverageFixtures.find(item=>item.stackId===product)!;const sources=Object.fromEntries(['a','b'].flatMap(prefix=>Object.entries(fixture.sources).map(([path,source])=>[`${prefix}/${path}`,source])));const analysis=await analyze(sources);for(const prefix of ['a','b']){expect(analysis.edges.some(edge=>edge.kind==='uses-resource'&&analysis.nodes.find(node=>node.id===edge.source)?.path===`${prefix}/app.ts`)).toBe(true);const owner=analysis.architecture!.nodes.find(node=>node.architecture?.ownerPath===prefix&&['application','code-package'].includes(node.architecture.kind))!;expect(analysis.architecture!.edges.some(edge=>edge.source===owner.id&&analysis.architecture!.nodes.find(node=>node.id===edge.target)?.attributes.dictionaryStackId===product)).toBe(true);}});
});
