// @vitest-environment node
import { beforeAll, describe, expect, it } from 'vitest';
import { scanProjectFiles } from '../scan';
import { semanticInput } from './client';
import { analyzeSemanticSources } from './analyze';
import { initializeTestParser, testLanguage, testParser } from './testRuntime';
import { frameworkCoverageFixtures } from '../fixtures/stack-coverage/frameworks';
import { uiCoverageFixtures } from '../fixtures/stack-coverage/ui';
import { projectSemanticView } from './project';
beforeAll(initializeTestParser);
async function analyze(sources:Record<string,string>){const store=await scanProjectFiles(Object.entries(sources).map(([relativePath,source])=>({relativePath,name:relativePath.split('/').at(-1)!,extension:'.'+relativePath.split('.').at(-1),size:source.length,readText:async()=>source})));return analyzeSemanticSources(semanticInput(store),testLanguage,undefined,testParser);}
describe('finite framework registration forms',()=>{
  it('attaches Fastify request/response schemas only to a bound registered route',async()=>{const fixture=frameworkCoverageFixtures.find(item=>item.stackId==='fastify')!;const analysis=await analyze(fixture.sources);expect(analysis.edges.some(edge=>edge.kind==='validates-input')).toBe(true);expect(analysis.edges.some(edge=>edge.kind==='response-schema')).toBe(true);const request=analysis.nodes.find(node=>node.label==='GET /api/users querystring')!;expect(request.fields).toMatchObject([{name:'name',type:'string',optional:false}]);});
  it('requires SvelteKit server actions and a directly resolved action function',async()=>{const base={'package.json':'{"dependencies":{"@sveltejs/kit":"2"}}'};const client=await analyze({...base,'src/routes/+page.ts':'export const actions={default:()=>({ok:true})};'});expect(client.nodes.some(node=>node.attributes.action)).toBe(false);const factory=await analyze({...base,'src/routes/+page.server.ts':'export const actions={default:wrapper(()=>({ok:true}))};'});const action=factory.nodes.find(node=>node.attributes.action==='default')!;expect(action.confidence).toBe('unresolved');expect(factory.edges.some(edge=>edge.source===action.id&&edge.kind==='handles')).toBe(false);});
  it('does not publish an unexported Astro GET function',async()=>{const analysis=await analyze({'package.json':'{"dependencies":{"astro":"5"}}','src/pages/users.ts':'function GET(){return Response.json({ok:true});}'});expect(analysis.nodes.some(node=>node.kind==='entry'&&node.attributes.routeRegistrationVerified)).toBe(false);});
  it('rejects Angular component and Nest provider generic shadows',async()=>{const angular=uiCoverageFixtures.find(item=>item.stackId==='angular')!;const source=angular.sources['app.ts']!.replace("export const routes:Routes=[{path:'home',component:App}];","function define(App){const routes:Routes=[{path:'ghost',component:App}];}");const analysis=await analyze({...angular.sources,'app.ts':source});expect(analysis.edges.some(edge=>edge.kind==='routes-to-component')).toBe(false);const nest=frameworkCoverageFixtures.find(item=>item.stackId==='nestjs')!;const generic=await analyze({...nest.sources,'api.ts':nest.sources['api.ts']!.replace('class Api{','class Api<Service>{')});expect(generic.edges.some(edge=>edge.kind==='injects')).toBe(false);const omitted=await analyze({...nest.sources,'api.ts':nest.sources['api.ts']!.replace('controllers:[Api]','controllers:[]')});expect(omitted.nodes.some(node=>node.kind==='entry'&&node.attributes.dictionaryStackId==='nestjs'&&node.attributes.routeRegistrationVerified)).toBe(false);});
  it('resolves a Nest constructor after its Module provider/controller registration',async()=>{const fixture=frameworkCoverageFixtures.find(item=>item.stackId==='nestjs')!;const analysis=await analyze(fixture.sources);const api=analysis.nodes.find(node=>node.kind==='model'&&node.label==='Api')!,service=analysis.nodes.find(node=>node.kind==='model'&&node.label==='Service')!;expect(analysis.edges.some(edge=>edge.source===api.id&&edge.target===service.id&&edge.kind==='injects')).toBe(true);const negative=await analyze({...fixture.sources,'api.ts':fixture.sources['api.ts']!.replace('providers:[Service]','providers:[]')});expect(negative.edges.some(edge=>edge.kind==='injects')).toBe(false);});
  it('connects SvelteKit load and actions handlers to their response values',async()=>{const fixture=uiCoverageFixtures.find(item=>item.stackId==='sveltekit')!;const analysis=await analyze(fixture.sources);const action=analysis.nodes.find(node=>node.kind==='entry'&&node.attributes.action==='default')!;expect(action.attributes).toMatchObject({method:'POST',endpoint:'/'});const target=analysis.edges.find(edge=>edge.source===action.id&&edge.kind==='handles')!.target;expect(analysis.nodes.find(node=>node.id===target)?.kind).toBe('function');expect(analysis.nodes.some(node=>node.kind==='entry'&&analysis.edges.some(edge=>edge.source===node.id&&edge.kind==='handles'&&analysis.nodes.find(fn=>fn.id===edge.target)?.attributes.name==='load'))).toBe(true);expect(projectSemanticView(analysis,'data-flow').nodes.some(node=>node.path==='src/routes/+page.server.ts'&&node.data?.role==='return')).toBe(true);});
  it('connects Angular Input and typed Routes to the declared component',async()=>{const fixture=uiCoverageFixtures.find(item=>item.stackId==='angular')!;const analysis=await analyze(fixture.sources);expect(analysis.edges.some(edge=>edge.kind==='routes-to-component')).toBe(true);const model=analysis.nodes.find(node=>node.kind==='model'&&node.label==='App')!;expect(model.fields?.find(field=>field.name==='title')?.constraints).toContain('component-input');expect(analysis.edges.some(edge=>edge.kind==='component-prop'&&edge.target===model.id)).toBe(true);});
  it('keeps Astro server endpoints and island/page entry kinds separate',async()=>{const fixture=uiCoverageFixtures.find(item=>item.stackId==='astro')!;const analysis=await analyze(fixture.sources);expect(analysis.nodes.some(node=>node.kind==='entry'&&node.attributes.endpoint==='/users'&&node.attributes.method==='GET')).toBe(true);expect(analysis.nodes.some(node=>node.kind==='entry'&&node.attributes.endpoint==='/'&&node.attributes.method==='PAGE')).toBe(true);expect(analysis.edges.some(edge=>edge.kind==='hydrates-island')).toBe(true);});
  it('recognizes an imported Spring Bean factory and excludes commented/lookalike annotations',async()=>{const base=frameworkCoverageFixtures.find(item=>item.stackId==='spring-framework')!.sources;const source='package demo; import org.springframework.context.annotation.Bean; class Service{} class Config{ @Bean Service service(){return new Service();}}';const analysis=await analyze({...base,'Config.java':source});expect(analysis.edges.some(edge=>edge.kind==='provider-factory'&&edge.evidence.some(at=>at.path==='Config.java'))).toBe(true);const negative=await analyze({...base,'Config.java':source.replace('org.springframework.context.annotation.Bean','custom.Bean')});expect(negative.edges.some(edge=>edge.kind==='provider-factory'&&edge.evidence.some(at=>at.path==='Config.java'))).toBe(false);});
});
