import runtime from 'web-tree-sitter/web-tree-sitter.wasm?url';
import legacyRuntime from 'web-tree-sitter-legacy/tree-sitter.wasm?url';
import typescript from '@repomix/tree-sitter-wasms/out/tree-sitter-typescript.wasm?url';
import tsx from '@repomix/tree-sitter-wasms/out/tree-sitter-tsx.wasm?url';
import javascript from '@repomix/tree-sitter-wasms/out/tree-sitter-javascript.wasm?url';
import python from '@repomix/tree-sitter-wasms/out/tree-sitter-python.wasm?url';
import java from '@repomix/tree-sitter-wasms/out/tree-sitter-java.wasm?url';
import c_sharp from '@repomix/tree-sitter-wasms/out/tree-sitter-c_sharp.wasm?url';
import go from '@repomix/tree-sitter-wasms/out/tree-sitter-go.wasm?url';
import rust from '@repomix/tree-sitter-wasms/out/tree-sitter-rust.wasm?url';
import ruby from '@repomix/tree-sitter-wasms/out/tree-sitter-ruby.wasm?url';
import php from '@repomix/tree-sitter-wasms/out/tree-sitter-php.wasm?url';
import c from '@repomix/tree-sitter-wasms/out/tree-sitter-c.wasm?url';
import cpp from '@repomix/tree-sitter-wasms/out/tree-sitter-cpp.wasm?url';
import swift from '@repomix/tree-sitter-wasms/out/tree-sitter-swift.wasm?url';
import dart from '@repomix/tree-sitter-wasms/out/tree-sitter-dart.wasm?url';
import kotlin from 'tree-sitter-wasms/out/tree-sitter-kotlin.wasm?url';
import scala from 'tree-sitter-wasms/out/tree-sitter-scala.wasm?url';
export const parserRuntimeUrl = runtime;
export const legacyParserRuntimeUrl = legacyRuntime;
export const grammarUrls: Record<string, string> = { typescript, tsx, javascript, python, java, c_sharp, go, rust, ruby, php, c, cpp, swift, dart, kotlin, scala };
