// @vitest-environment node
import { beforeAll, describe, expect, it } from 'vitest';
import { analyzeSemanticSources } from './analyze';
import { initializeTestParser, testLanguage, testParser } from './testRuntime';
import { projectSemanticView } from './project';
beforeAll(initializeTestParser);
describe('JSX/TSX props and render values',()=>{
 it.each(['jsx','tsx'])('%s preserves the bound declaration through prop and render input',async extension=>{const path=`App.${extension}`;const source="import{useState}from'react';function Child({value}){return <p>{value}</p>;}export function App(){const[name,setName]=useState('Alice');return <Child value={name}/>;}";const analysis=await analyzeSemanticSources({sources:{[path]:source},imports:[],resources:[]},testLanguage,undefined,testParser);const flow=projectSemanticView(analysis,'data-flow');const prop=flow.nodes.find(node=>node.attributes.jsxProp&&node.data?.propertyPath?.[0]==='value')!;expect(prop).toBeDefined();const incoming=flow.edges.find(edge=>edge.target===prop.id&&edge.kind==='jsx-prop-value')!;const use=flow.nodes.find(node=>node.id===incoming.source)!;expect(use.data?.declarationId).toBeDefined();expect(flow.edges.some(edge=>edge.target===use.id&&edge.kind==='origin')).toBe(true);expect(source.slice(prop.evidence[0]!.start,prop.evidence[0]!.end)).toBe('value={name}');const props=flow.edges.find(edge=>edge.source===prop.id&&edge.kind==='jsx-prop')!.target;expect(flow.edges.some(edge=>edge.source===props&&edge.kind==='component-input')).toBe(true);expect(flow.edges.some(edge=>edge.source===props&&edge.kind==='passes-to')).toBe(true);});
 it('keeps a shadowing JSX value parameter separate from an outer state declaration',async()=>{const source="const name='outer';function Child({value}){return <p>{value}</p>;}function render(name){return <Child value={name}/>;}";const analysis=await analyzeSemanticSources({sources:{'App.tsx':source},imports:[],resources:[]},testLanguage,undefined,testParser);const flow=projectSemanticView(analysis,'data-flow');const prop=flow.nodes.find(node=>node.attributes.jsxProp)!;const input=flow.nodes.find(node=>node.id===flow.edges.find(edge=>edge.target===prop.id&&edge.kind==='jsx-prop-value')!.source)!;const declaration=flow.nodes.find(node=>node.id===input.data?.declarationId)!;expect(declaration.attributes.ownerName).toBe('render');expect(declaration.data?.role).toBe('parameter');});
});
