// @vitest-environment node
import { beforeAll, describe, expect, it } from 'vitest';
import { scanProjectFiles } from '../scan';
import { semanticInput } from './client';
import { analyzeSemanticSources } from './analyze';
import { initializeTestParser, testLanguage, testParser } from './testRuntime';
import { frameworkCoverageFixtures } from '../fixtures/stack-coverage/frameworks';
beforeAll(initializeTestParser);
async function analyze(sources:Record<string,string>){const store=await scanProjectFiles(Object.entries(sources).map(([relativePath,source])=>({relativePath,name:relativePath.split('/').at(-1)!,extension:'.'+relativePath.split('.').at(-1),size:source.length,readText:async()=>source})));return analyzeSemanticSources(semanticInput(store),testLanguage,undefined,testParser);}
describe('native framework registration',()=>{
 it.each(['gin','axum'])('%s keeps group/nest prefix and actual handler provenance',async product=>{const fixture=frameworkCoverageFixtures.find(item=>item.stackId===product)!;const analysis=await analyze(fixture.sources);const entries=analysis.nodes.filter(node=>node.kind==='entry'&&node.attributes.endpoint);expect(entries.map(node=>node.attributes.endpoint)).toEqual(['/api/users']);const entry=entries[0]!;expect(entry.evidence.some(at=>at.description?.includes(product==='gin'?'Group':'nest'))).toBe(true);expect(analysis.edges.some(edge=>edge.source===entry.id&&edge.kind==='handles'&&analysis.nodes.find(node=>node.id===edge.target)?.attributes.name==='users')).toBe(true);});
 it('keeps Actix service registration and typed extractor input',async()=>{const fixture=frameworkCoverageFixtures.find(item=>item.stackId==='actix-web')!;const analysis=await analyze(fixture.sources);expect(analysis.edges.some(edge=>edge.kind==='registers-service')).toBe(true);expect(analysis.edges.some(edge=>edge.kind==='extractor-input'&&analysis.nodes.find(node=>node.id===edge.source)?.label==='User')).toBe(true);});
 it('requires ASP controller mapping and keeps the route attribute range',async()=>{const fixture=frameworkCoverageFixtures.find(item=>item.stackId==='aspnet-core')!;const analysis=await analyze(fixture.sources);const entry=analysis.nodes.find(node=>node.kind==='entry'&&node.attributes.endpoint==='/api/users')!;expect(entry.path).toBe('UsersController.cs');expect(fixture.sources[entry.path!]!.slice(entry.evidence[0]!.start,entry.evidence[0]!.end)).toBe('[HttpGet]');const negative=await analyze({...fixture.sources,'Program.cs':fixture.sources['Program.cs']!.replace('app.MapControllers();','')});expect(negative.nodes.some(node=>node.kind==='entry'&&node.attributes.routeRegistrationVerified)).toBe(false);});
 it.each(['gin','axum'])('does not promote a custom %s router implementation',async product=>{const fixture=frameworkCoverageFixtures.find(item=>item.stackId===product)!;const sources=Object.fromEntries(Object.entries(fixture.sources).map(([path,source])=>[path,path.endsWith('.go')?source.replace('github.com/gin-gonic/gin','example.test/custom'):path.endsWith('.rs')?source.replace('use axum::','use custom::'):source]));const analysis=await analyze(sources);expect(analysis.nodes.some(node=>node.kind==='entry'&&node.attributes.routeRegistrationVerified)).toBe(false);});
});
