// @vitest-environment node
import{beforeAll,describe,expect,it}from'vitest';
import{queryCoverageFixtures}from'../fixtures/stack-coverage/queries';
import{scanProjectFiles}from'../scan';
import{semanticInput}from'./client';
import{analyzeSemanticSources}from'./analyze';
import{initializeTestParser,testLanguage,testParser}from'./testRuntime';
import{projectSemanticView}from'./project';
beforeAll(initializeTestParser);
async function analyze(sources:Record<string,string>){const store=await scanProjectFiles(Object.entries(sources).map(([relativePath,source])=>({relativePath,name:relativePath.split('/').at(-1)!,extension:'.'+relativePath.split('.').at(-1),size:source.length,readText:async()=>source})));return{store,analysis:await analyzeSemanticSources(semanticInput(store),testLanguage,undefined,testParser)};}
describe('query language operation AST and explicit resolver registration',()=>{
  it('preserves PostgreSQL quoted identifier case when resolving table references',async()=>{const{analysis}=await analyze({'schema.sql':'CREATE TABLE "Users" (id integer);','read.sql':'SELECT id FROM users; SELECT id FROM "Users";'});const reads=analysis.edges.filter(edge=>edge.kind==='reads-table');expect(reads).toHaveLength(1);expect(analysis.nodes.find(node=>node.id===reads[0]!.target)?.data?.expression).toContain('"Users"');});
  it('selects each explicitly passed GraphQL schema and rejects unknown schemas or invalid fields',async()=>{const{analysis}=await analyze({'app.ts':"import{buildSchema,graphql}from'graphql';const a=buildSchema(`type A{id:ID} type Query{a:A}`);const b=buildSchema(`type B{name:String} type Query{b:B}`);function loadA(){return{id:'1'}}function loadB(){return{name:'B'}};graphql({schema:a,source:'{a{id}}',rootValue:{a:loadA}});graphql({schema:b,source:'{b{name}}',rootValue:{b:loadB}});function unknown(schema){return graphql({schema,source:'{a{id}}',rootValue:{a:loadA}});}graphql({schema:a,source:'{ghost}',rootValue:{ghost:loadA}});"});const outputs=analysis.edges.filter(edge=>edge.kind==='query-output');expect(outputs.map(edge=>analysis.nodes.find(node=>node.id===edge.target)?.label).sort()).toEqual(['A','B']);expect(analysis.edges.filter(edge=>edge.kind==='resolver')).toHaveLength(2);expect(analysis.nodes.filter(node=>node.kind==='model'&&node.label==='Query').map(node=>node.fields?.map(field=>field.name))).toEqual([['a'],['b']]);});
  it('does not turn quoted SQL text or GraphQL descriptions into declarations',async()=>{const{analysis}=await analyze({'sample.sql':"SELECT 'CREATE TABLE fake (id integer);';",'schema.graphql':'"""type Fake { ghost: String }"""\ntype User { id: ID! }'});expect(analysis.nodes.some(node=>node.kind==='model'&&/fake/i.test(node.label))).toBe(false);expect(analysis.nodes.some(node=>node.kind==='model'&&node.label==='User')).toBe(true);});
  it.each(queryCoverageFixtures)('$fixtureId keeps query/mutation, fields and exact source provenance',async fixture=>{const{store,analysis}=await analyze(fixture.sources);expect(store.facts.some(fact=>fact.kind==='technology'&&fact.dictionaryStackId===fixture.stackId)).toBe(true);for(const kind of fixture.edges)expect(analysis.edges.some(edge=>edge.kind===kind),kind).toBe(true);expect(projectSemanticView(analysis,'data-model').nodes.some(node=>node.fields?.some(field=>field.name==='name'))).toBe(true);expect(projectSemanticView(analysis,'runtime-flow').edges.some(edge=>edge.kind==='executes')).toBe(true);for(const edge of analysis.edges.filter(edge=>(fixture.edges as readonly string[]).includes(edge.kind)))for(const at of edge.evidence){const source=(fixture.sources as Record<string,string>)[at.path]!;expect(at.end).toBeGreaterThan(at.start);expect(source.slice(0,at.start).split('\n').length).toBe(at.line);}
    if(fixture.stackId==='sql'){expect(analysis.nodes.filter(node=>node.id.startsWith('query:operation:')).map(node=>node.label.split(' ')[0]).sort()).toEqual(['DELETE','INSERT','SELECT','UPDATE']);}else{const resolvers=analysis.edges.filter(edge=>edge.kind==='resolver');expect(resolvers).toHaveLength(2);expect(resolvers.map(edge=>analysis.nodes.find(node=>node.id===edge.target)?.attributes.name).sort()).toEqual(['save','users']);expect(projectSemanticView(analysis,'function-call-flow').edges.some(edge=>edge.kind==='calls')).toBe(true);}
  });
  it.each(queryCoverageFixtures)('$fixtureId ignores commented definitions/operations',async fixture=>{const sources=Object.fromEntries(Object.entries(fixture.sources).map(([path,source])=>[path,path.endsWith('.sql')?source.split('\n').map(line=>'-- '+line).join('\n'):path.endsWith('.ts')?source.split('\n').map(line=>'// '+line).join('\n'):source]));const{analysis}=await analyze(sources);expect(analysis.nodes.some(node=>node.id.startsWith('query:operation:'))).toBe(false);expect(analysis.edges.some(edge=>edge.kind==='resolver')).toBe(false);});
  it.each(queryCoverageFixtures)('$fixtureId keeps duplicate schema names in their owner projects',async fixture=>{const sources=Object.fromEntries(['a','b'].flatMap(prefix=>Object.entries(fixture.sources).map(([path,source])=>[`${prefix}/${path}`,source])));const{analysis}=await analyze(sources);for(const edge of analysis.edges.filter(edge=>(fixture.edges as readonly string[]).includes(edge.kind))){const from=analysis.nodes.find(node=>node.id===edge.source)!;const to=analysis.nodes.find(node=>node.id===edge.target)!;expect(from.path?.split('/')[0]).toBe(to.path?.split('/')[0]);}});
  it('does not interpret arbitrary SQL/GraphQL strings or fake graphql functions as execution',async()=>{const{analysis}=await analyze({'package.json':'{"dependencies":{"graphql":"17"}}','app.ts':"const query='query Ghost { users { id } }';function graphql(options){return options;}graphql({source:query,rootValue:{users(){return []}}});const sql='DELETE FROM users';"});expect(analysis.nodes.some(node=>node.id.startsWith('query:'))).toBe(false);});
});
