import ts from 'typescript';
import type { ASTNode, DocumentNode, FieldNode, OperationDefinitionNode } from 'graphql';
import type { Statement, PGNode, QName } from 'pgsql-ast-parser';
import { sourceEvidence, visitSource, type DataCompiler } from './dataCompiler';
import type { SemanticAnalysis, SemanticEvidence, SemanticInput, SemanticNode, SemanticViewId } from './types';

/** Query parsers are loaded only for query-language files or explicit GraphQL API imports. */
export async function refineQuerySemantics(analysis:SemanticAnalysis,input:SemanticInput,compiler:DataCompiler){
  const owner=(path:string)=>input.projectScopes?.filter(scope=>scope.directory==='.'||path.startsWith(scope.directory+'/')).sort((a,b)=>b.directory.length-a.directory.length)[0]?.id??'.';
  const evidence=(path:string,start:number,end:number,description:string):SemanticEvidence=>({path,start,end,line:input.sources[path]!.slice(0,start).split('\n').length,endLine:input.sources[path]!.slice(0,end).split('\n').length,description});
  const node=(kind:SemanticNode['kind'],label:string,path:string,start:number,end:number,product:string)=>{const at=evidence(path,start,end,label);const item:SemanticNode={id:`query:${kind}:${path}:${start}:${end}:${label}`,kind,label,path,line:at.line,endLine:at.endLine,language:product,group:kind==='model'?'Data models':'Persistence',confidence:'source',evidence:[at],attributes:{dictionaryStackId:product,technologyName:product==='sql'?'SQL':'GraphQL'}};analysis.nodes.push(item);return item;};
  const edge=(from:SemanticNode,to:SemanticNode,kind:string,views:SemanticViewId[],at:SemanticEvidence[])=>{const id=`query:${kind}:${from.id}:${to.id}`;if(!analysis.edges.some(item=>item.id===id))analysis.edges.push({id,source:from.id,target:to.id,kind,label:kind.replaceAll('-',' '),views,confidence:'source',evidence:at});};
  const sqlSources=Object.entries(input.sources).filter(([path])=>path.endsWith('.sql'));
  if(sqlSources.length){const{parse,locationOf}=await import('pgsql-ast-parser');
    const discarded=new Set<string>();
    const qualified=(name:QName)=>[name.schema,name.name].filter(Boolean).join('.');
    const tables=analysis.nodes.filter(item=>item.kind==='model'&&item.attributes.modelKind==='sql');for(const table of tables)table.attributes.dictionaryStackId='sql';
    const tableNames=new Map<string,string>();for(const[path,source]of sqlSources)try{for(const statement of parse(source,{locationTracking:true})){if(statement.type!=='create table')continue;const range=locationOf(statement);for(const table of tables.filter(table=>table.path===path&&table.evidence.some(at=>at.start===range.start)))tableNames.set(table.id,qualified(statement.name));}}catch{/* unsupported dialect stays partial below */}
    const tableFor=(name:QName,path:string)=>{const matches=tables.filter(table=>!discarded.has(table.id)&&owner(table.path!)===owner(path)&&tableNames.get(table.id)===qualified(name));return matches.length===1?matches[0]:undefined;};
    for(const[path,source]of sqlSources){let statements:Statement[];try{statements=parse(source,{locationTracking:true});}catch{const coverage=analysis.coverage.find(item=>item.path===path);if(coverage){coverage.status='partial';coverage.message=(coverage.message?coverage.message+' ':'')+'既存DDLの対応範囲を保持。問い合わせASTはPostgreSQL互換の対応構文に限定され、このファイルは未展開です。';}continue;}
      const declarations=statements.filter(statement=>statement.type==='create table').map(statement=>locationOf(statement));for(const model of tables.filter(table=>table.path===path))if(!declarations.some(range=>model.evidence.some(at=>at.start===range.start)))discarded.add(model.id);
      for(const statement of statements){if(!['select','insert','update','delete'].includes(statement.type))continue;const range=locationOf(statement);const operation=node('operation',`${statement.type.toUpperCase()} · ${path.split('/').at(-1)}`,path,range.start,range.end,'sql');operation.attributes.operation='database';operation.data={role:'operation',expression:source.slice(range.start,range.end),resolution:'partial',reasons:['SQL宣言。実行結果・接続先は未観測']};
        const entry=node('entry',`SQL statement · L${operation.line}`,path,range.start,range.end,'sql');entry.attributes.queryStatement=true;edge(entry,operation,'executes',['runtime-flow'],operation.evidence);
        const references:{name:QName;write:boolean;ast:PGNode}[]=[];
        if(statement.type==='insert')references.push({name:statement.into,write:true,ast:statement.into});if(statement.type==='update')references.push({name:statement.table,write:true,ast:statement.table});if(statement.type==='delete')references.push({name:statement.from,write:true,ast:statement.from});
        const walk=(value:unknown)=>{if(!value||typeof value!=='object')return;if(Array.isArray(value)){value.forEach(walk);return;}const object=value as Record<string,unknown>;if(object.type==='table'&&object.name)references.push({name:object.name as QName,write:false,ast:value as PGNode});for(const[key,child]of Object.entries(object))if(key!=='_location')walk(child);};walk(statement);
        for(const reference of references){const table=tableFor(reference.name,path);if(!table){operation.confidence='unresolved';continue;}const at=locationOf(reference.ast);edge(reference.write?operation:table,reference.write?table:operation,reference.write?'writes-table':'reads-table',['runtime-flow','data-flow'],[evidence(path,at.start,at.end,'SQL ASTのテーブル参照'),...table.evidence]);}
      }
    }
    analysis.nodes=analysis.nodes.filter(node=>!discarded.has(node.id));analysis.edges=analysis.edges.filter(edge=>!discarded.has(edge.source)&&!discarded.has(edge.target));
  }
  const graphqlFiles=Object.entries(input.sources).filter(([path])=>/\.(graphql|gql)$/.test(path));
  const graphqlScripts=[...compiler.files.values()].filter(file=>file.statements.some(statement=>ts.isImportDeclaration(statement)&&ts.isStringLiteralLike(statement.moduleSpecifier)&&statement.moduleSpecifier.text==='graphql'));
  if(!graphqlFiles.length&&!graphqlScripts.length)return;
  const{parse,print,Kind}=await import('graphql/language');
  interface Document {path:string;offset:number;document:DocumentNode;call?:ts.CallExpression;root?:ts.ObjectLiteralExpression;schemaSpecified?:boolean;schemaCall?:ts.CallExpression}
  const documents:Document[]=[];
  const addDocument=(path:string,source:string,offset=0,call?:ts.CallExpression,root?:ts.ObjectLiteralExpression,schemaSpecified=false,schemaCall?:ts.CallExpression)=>{try{documents.push({path,offset,document:parse(source),call,root,schemaSpecified,schemaCall});}catch{analysis.coverage.push({path,language:'graphql',status:'partial',message:'GraphQL文書の構文を解析できません。動的補間は未評価です。'});}};
  for(const[path,source]of graphqlFiles)addDocument(path,source);
  for(const file of graphqlScripts){const imports=new Map<ts.Symbol,string>();for(const statement of file.statements)if(ts.isImportDeclaration(statement)&&ts.isStringLiteralLike(statement.moduleSpecifier)&&statement.moduleSpecifier.text==='graphql'&&statement.importClause?.namedBindings&&ts.isNamedImports(statement.importClause.namedBindings))for(const item of statement.importClause.namedBindings.elements){const symbol=compiler.checker.getSymbolAtLocation(item.name);if(symbol)imports.set(symbol,item.propertyName?.text??item.name.text);}
    const resolve=(expression:ts.Expression,seen=new Set<ts.Symbol>()):ts.Expression=>{if(!ts.isIdentifier(expression))return expression;const symbol=compiler.symbol(expression);if(!symbol||seen.has(symbol))return expression;const declaration=symbol.valueDeclaration;return declaration&&ts.isVariableDeclaration(declaration)&&declaration.initializer?resolve(declaration.initializer,new Set([...seen,symbol])):expression;};
    const literal=(expression:ts.Expression|undefined)=>{if(!expression)return;const value=resolve(expression);if(!ts.isStringLiteralLike(value)&&!ts.isNoSubstitutionTemplateLiteral(value))return;if(value.getText().slice(1,-1)!==value.text)return;return value;};
    visitSource(file,current=>{if(!ts.isCallExpression(current)||!ts.isIdentifier(current.expression))return;const symbol=compiler.checker.getSymbolAtLocation(current.expression);const name=symbol?imports.get(symbol):undefined;if(name==='buildSchema'||name==='parse'){const source=literal(current.arguments[0]);if(source)addDocument(file.fileName,source.text,source.getStart()+1,current);}
      if(name==='graphql'||name==='graphqlSync'){const argument=current.arguments[0];const options=argument?resolve(argument):undefined;if(!options||!ts.isObjectLiteralExpression(options))return;const property=(key:string)=>{const member=options.properties.find(item=>item.name?.getText()===key);return member&&ts.isPropertyAssignment(member)?member.initializer:member&&ts.isShorthandPropertyAssignment(member)?member.name:undefined;};const source=literal(property('source'));const rootExpression=property('rootValue');const root=rootExpression?resolve(rootExpression):undefined;const schemaExpression=property('schema');const schema=schemaExpression?resolve(schemaExpression):undefined;if(source)addDocument(file.fileName,source.text,source.getStart()+1,current,root&&ts.isObjectLiteralExpression(root)?root:undefined,true,schema&&ts.isCallExpression(schema)?schema:undefined);}
    });
  }
  const at=(document:Document,ast:ASTNode,description:string)=>evidence(document.path,document.offset+(ast.loc?.start??0),document.offset+(ast.loc?.end??0),description);
  const models:{node:SemanticNode;document:Document}[]=[];
  for(const document of documents)for(const definition of document.document.definitions){if(![Kind.OBJECT_TYPE_DEFINITION,Kind.INPUT_OBJECT_TYPE_DEFINITION,Kind.INTERFACE_TYPE_DEFINITION,Kind.ENUM_TYPE_DEFINITION].includes(definition.kind as typeof Kind.OBJECT_TYPE_DEFINITION))continue;if(!('name'in definition)||!definition.name)continue;
    const range=at(document,definition,'GraphQL SDL definition');const existing=analysis.nodes.find(item=>item.kind==='model'&&item.path===document.path&&item.label===definition.name!.value&&item.attributes.modelKind==='graphql'&&item.evidence.some(at=>at.start===range.start));const model=existing??node('model',definition.name.value,document.path,range.start,range.end,'graphql');model.evidence=[range];model.attributes.dictionaryStackId='graphql';model.attributes.modelKind='graphql';model.model={domain:'code',kind:definition.kind===Kind.ENUM_TYPE_DEFINITION?'enum':'object',definition:input.sources[document.path]!.slice(range.start,range.end),expansion:'expanded',reasons:[]};
    if('fields'in definition&&definition.fields)model.fields=definition.fields.map(field=>({id:`${model.id}:field:${field.name.value}`,name:field.name.value,type:print(field.type),optional:field.type.kind!==Kind.NON_NULL_TYPE,nullable:field.type.kind!==Kind.NON_NULL_TYPE,array:print(field.type).includes('['),evidence:[at(document,field,'GraphQL field declaration')]}));models.push({node:model,document});
  }
  const parsedPaths=new Set(documents.filter(document=>graphqlFiles.some(([path])=>path===document.path)).map(document=>document.path));const validIds=new Set(models.map(item=>item.node.id));const discarded=new Set(analysis.nodes.filter(node=>node.kind==='model'&&node.attributes.modelKind==='graphql'&&parsedPaths.has(node.path!)&&!validIds.has(node.id)).map(node=>node.id));analysis.nodes=analysis.nodes.filter(node=>!discarded.has(node.id));analysis.edges=analysis.edges.filter(edge=>!discarded.has(edge.source)&&!discarded.has(edge.target));
  for(const{node:model,document}of models)for(const field of model.fields??[]){const name=field.type.replace(/[\]![]/g,'');const matches=models.filter(item=>(document.call?item.document===document:owner(item.document.path)===owner(document.path)&&!item.document.call)&&item.node.label===name);if(matches.length===1){field.referenceIds=[matches[0]!.node.id];edge(model,matches[0]!.node,'field-type',['data-model'],field.evidence!);}}
  for(const document of documents)for(const definition of document.document.definitions){if(definition.kind!==Kind.OPERATION_DEFINITION)continue;const operationDefinition:OperationDefinitionNode=definition;const range=at(document,definition,'GraphQL operation');const entry=node('entry',`${definition.operation} ${definition.name?.value??'(anonymous)'}`,document.path,range.start,range.end,'graphql');entry.attributes.queryOperation=definition.operation;
    const variables=definition.variableDefinitions??[];if(variables.length){const shape=node('model',`${entry.label} variables`,document.path,range.start,range.end,'graphql');shape.fields=variables.map(variable=>({name:variable.variable.name.value,type:print(variable.type),optional:variable.type.kind!==Kind.NON_NULL_TYPE,evidence:[at(document,variable,'GraphQL variable definition')]}));shape.model={domain:'code',kind:'object',definition:print(definition),expansion:'expanded',reasons:[]};edge(shape,entry,'query-input',['data-flow'],shape.evidence);}
    const schemaModels=models.filter(item=>document.schemaSpecified?Boolean(document.schemaCall)&&item.document.call===document.schemaCall:owner(item.document.path)===owner(document.path)&&!item.document.call);const roots=schemaModels.filter(item=>item.node.label===(definition.operation==='mutation'?'Mutation':'Query'));
    for(const selection of operationDefinition.selectionSet.selections){if(selection.kind!==Kind.FIELD)continue;const field:FieldNode=selection;const fieldRange=at(document,field,'GraphQL selection');const operation=node('operation',`${definition.operation} ${field.name.value}`,document.path,fieldRange.start,fieldRange.end,'graphql');operation.data={role:'operation',expression:input.sources[document.path]!.slice(fieldRange.start,fieldRange.end),resolution:'partial'};edge(entry,operation,'executes',['runtime-flow'],operation.evidence);
      if(roots.length===1){const root=roots[0]!.node;const selected=root.fields?.find(item=>item.name===field.name.value);if(selected){edge(operation,root,'selects-field',['data-flow'],[fieldRange,...selected.evidence??[]]);const result=schemaModels.filter(item=>item.node.label===selected.type.replace(/[\]![]/g,''));if(result.length===1)edge(operation,result[0]!.node,'query-output',['data-flow'],operation.evidence);}else operation.confidence='unresolved';}else operation.confidence='unresolved';
      if(operation.confidence==='unresolved')continue;
      const registration=document.root?.properties.find(property=>property.name?.getText()===field.name.value);let targetAst:ts.Node|undefined=registration&&ts.isPropertyAssignment(registration)?registration.initializer:registration&&ts.isShorthandPropertyAssignment(registration)?registration.name:registration;if(targetAst&&ts.isIdentifier(targetAst)){const symbol=compiler.symbol(targetAst);targetAst=symbol?.valueDeclaration;if(targetAst&&ts.isVariableDeclaration(targetAst))targetAst=targetAst.initializer;}
      if(targetAst&&(ts.isFunctionDeclaration(targetAst)||ts.isArrowFunction(targetAst)||ts.isFunctionExpression(targetAst)||ts.isMethodDeclaration(targetAst))){const target=analysis.nodes.filter(item=>item.kind==='function'&&!item.attributes.initializer&&item.path===targetAst!.getSourceFile().fileName&&item.evidence.some(ev=>ev.start>=targetAst!.getStart()&&ev.end<=targetAst!.end));if(target.length===1)edge(operation,target[0]!,'resolver',['runtime-flow','function-call-flow'],[fieldRange,...registration?[sourceEvidence(registration,'graphql rootValueの明示登録')]:[]]);}
    }
  }
}
