// @vitest-environment node
import { frameworkRegistrationFixtures } from '../fixtures/stack-coverage/frameworkRegistration';
import { beforeAll, describe, expect, it } from 'vitest';
import { scanProjectFiles } from '../scan';
import { semanticInput } from './client';
import { analyzeSemanticSources } from './analyze';
import { initializeTestParser, testLanguage, testParser } from './testRuntime';
beforeAll(initializeTestParser);
async function analyze(sources:Record<string,string>){const store=await scanProjectFiles(Object.entries(sources).map(([relativePath,source])=>({relativePath,name:relativePath.split('/').at(-1)!,extension:'.'+relativePath.split('.').at(-1),size:source.length,readText:async()=>source})));return analyzeSemanticSources(semanticInput(store),testLanguage,undefined,testParser);}
const fixtures=frameworkRegistrationFixtures;
describe('static Python router registration',()=>{
 it('keeps the FastAPI app to router to endpoint registration path',async()=>{const analysis=await analyze(fixtures.fastapi!);const mount=analysis.edges.find(edge=>edge.kind==='registers-router')!;const routes=analysis.edges.filter(edge=>edge.source===mount.target&&edge.kind==='registers-route');expect(routes).toHaveLength(2);for(const route of routes)expect(analysis.edges.some(edge=>edge.source===route.target&&edge.kind==='handles')).toBe(true);});
 it('preserves Django trailing slash and project-relative qualified URLconf imports',async()=>{const sources={'pyproject.toml':'[project]\nname="api"\ndependencies=["django"]','urls.py':"from django.urls import path,include\nurlpatterns=[path('api/',include('app.users'))]",'app/users.py':"from django.urls import path\ndef users(request):\n return {}\nurlpatterns=[path('users/',users)]"};const analysis=await analyze(Object.fromEntries(['a','b'].flatMap(prefix=>Object.entries(sources).map(([path,source])=>[`${prefix}/${path}`,source]))));expect(analysis.nodes.filter(node=>node.kind==='entry'&&node.attributes.endpoint).map(node=>node.attributes.endpoint)).toEqual(['/api/users/','/api/users/']);});
 it('retains an unresolved Django include without a fake verified handler',async()=>{const analysis=await analyze({'pyproject.toml':'[project]\nname="api"\ndependencies=["django"]','urls.py':"from django.urls import path,include\nurlpatterns=[path('api/',include('missing.users'))]"});expect(analysis.nodes.some(node=>node.kind==='entry'&&node.attributes.routeRegistrationVerified)).toBe(false);expect(analysis.nodes.some(node=>node.kind==='entry'&&node.attributes.unresolvedHandler)).toBe(true);});
 it.each(Object.entries(fixtures))('%s composes only registered prefixes and real local handlers',async(product,sources)=>{const analysis=await analyze(sources);const routes=analysis.nodes.filter(node=>node.kind==='entry'&&node.attributes.endpoint);expect(routes.map(node=>node.attributes.endpoint).sort()).toEqual(product==='fastapi'?['/v1/api/users','/v2/api/users']:['/api/users']);for(const route of routes){const handler=analysis.edges.find(edge=>edge.source===route.id&&edge.kind==='handles')!.target;expect(analysis.nodes.find(node=>node.id===handler)?.attributes.name).toBe('users');expect(analysis.edges.some(edge=>edge.source===handler&&edge.kind==='calls'&&analysis.nodes.find(node=>node.id===edge.target)?.attributes.name==='load')).toBe(true);expect(route.evidence.length).toBeGreaterThan(1);}});
 it.each(['fastapi','flask'])('%s unregistered routers have no public endpoint',async product=>{const source=fixtures[product]!;const analysis=await analyze({...source,'app.py':source['app.py']!.split('\n').filter(line=>!line.includes('app.include_router')&&!line.includes('app.register_blueprint')).join('\n')});expect(analysis.nodes.some(node=>node.kind==='entry'&&node.attributes.endpoint)).toBe(false);});
 it.each(Object.entries(fixtures))('%s prefixes and handler identity stay in each project',async(product,sources)=>{const analysis=await analyze(Object.fromEntries(['a','b'].flatMap(prefix=>Object.entries(sources).map(([path,source])=>[`${prefix}/${path}`,source]))));const routes=analysis.nodes.filter(node=>node.kind==='entry'&&node.attributes.endpoint);expect(routes).toHaveLength(product==='fastapi'?4:2);for(const route of routes)for(const edge of analysis.edges.filter(edge=>edge.source===route.id&&edge.kind==='handles'))expect(analysis.nodes.find(node=>node.id===edge.target)?.path?.split('/')[0]).toBe(route.path?.split('/')[0]);});
});
