// @vitest-environment node
import{beforeAll,describe,expect,it}from'vitest';import{scanProjectFiles}from'./scan';import{projectCommand,projectModuleDependency,projectStackMap}from'./projectors';import{semanticInput}from'./semantic/client';import{analyzeSemanticSources}from'./semantic/analyze';import{initializeTestParser,testLanguage,testParser}from'./semantic/testRuntime';import{toolCoverageFixtures}from'./fixtures/stack-coverage/tooling';
beforeAll(initializeTestParser);
const scan=(sources:Record<string,string>)=>scanProjectFiles(Object.entries(sources).map(([relativePath,source])=>({relativePath,name:relativePath.split('/').at(-1)!,extension:'.'+relativePath.split('.').at(-1),size:source.length,readText:async()=>source})));
describe('static build entry / output configuration',()=>{
 it.each([
 ['build.mjs',"import * as esbuild from 'esbuild';esbuild.build({entryPoints:[{in:'src/main.ts',out:'decoy.ts'}],outfile:'bundle.js'});",'node build.mjs'],
 ['config/production.js','module.exports={"entry":{app:{import:"src/main.ts",filename:"decoy.ts"}},"output":{"filename":"bundle.js"}};','webpack --config config/production.js'],
 ])('uses real input fields in %s descriptors',async(path,source,command)=>{const store=await scan({'package.json':JSON.stringify({scripts:{build:command},dependencies:{esbuild:'0.25',webpack:'5'}}),[path]:source,'src/main.ts':'export const value=1;','decoy.ts':'export const decoy=1;'});expect(store.facts.filter(fact=>fact.kind==='module-dependency'&&fact.dependencyKind==='build-entry').map(fact=>fact.kind==='module-dependency'?fact.targetPath:undefined)).toEqual(['src/main.ts']);expect(store.facts.some(fact=>fact.metadata.buildOutput&&fact.metadata.outputPath==='bundle.js')).toBe(true);});
 it('ignores type-only esbuild imports and unknown later object spreads',async()=>{const store=await scan({'package.json':'{"dependencies":{"esbuild":"0.25","webpack":"5"}}','build.ts':"import{type build}from'esbuild';build({entryPoints:['src/main.ts'],outfile:'ghost.js'});",'webpack.config.js':"module.exports={entry:'src/main.ts',...unknown};",'src/main.ts':'export const value=1;'});expect(store.facts.some(fact=>fact.metadata.buildOutput||fact.kind==='module-dependency'&&fact.dependencyKind==='build-entry')).toBe(false);expect(store.warnings.some(warning=>warning.message.includes('静的に確定'))).toBe(true);});
 it('uses explicit fields after an unknown spread',async()=>{const store=await scan({'package.json':'{"dependencies":{"webpack":"5"}}','webpack.config.js':"module.exports={...unknown,entry:'src/main.ts',output:{filename:'bundle.js'}};",'src/main.ts':'export const value=1;'});expect(store.facts.filter(fact=>fact.kind==='module-dependency'&&fact.dependencyKind==='build-entry')).toHaveLength(1);});

 it.each(['webpack','esbuild'])('connects %s entry to declared artifact and command in its project',async product=>{const fixture=toolCoverageFixtures.find(item=>item.stackId===product)!;const store=await scan(fixture.sources);const entry=store.facts.find(fact=>fact.kind==='module-dependency'&&fact.dependencyKind==='build-entry')!;expect(entry).toMatchObject({targetPath:'src/main.ts'});const artifact=store.facts.find(fact=>fact.kind==='resource'&&fact.metadata.buildOutput)!;expect(artifact.metadata.inputPaths).toEqual(['src/main.ts']);expect(artifact.metadata.observed).toBe(false);expect(store.relations.some(relation=>relation.targetId===artifact.id&&relation.metadata.buildInputOutput)).toBe(true);expect(projectModuleDependency(store).edges.find(edge=>edge.metadata.dependencyKind==='build-entry')).toMatchObject({kind:'uses-config',label:'ビルド入力'});expect(projectCommand(store).nodes.some(node=>node.factId===artifact.id)).toBe(true);expect(projectStackMap(store).nodes.some(node=>node.metadata.stackId===product&&node.metadata.roleOrder===3)).toBe(true);const analysis=await analyzeSemanticSources(semanticInput(store),testLanguage,undefined,testParser);const output=analysis.architecture!.nodes.find(node=>node.attributes.buildOutput)!;expect(output.architecture).toMatchObject({kind:'resource'});expect(output.architecture?.parentId).toBeDefined();const inputEdge=analysis.architecture!.edges.find(edge=>edge.target===output.id&&edge.kind==='build-output')!;expect(inputEdge).toBeDefined();expect(analysis.architecture!.nodes.find(node=>node.id===inputEdge.source)?.architecture?.files).toContain('src/main.ts');});
 it('rejects lookalike esbuild calls and commented webpack entries',async()=>{const store=await scan({'package.json':'{"dependencies":{"esbuild":"0.25","webpack":"5"}}','build.ts':"import{build as bundle}from'esbuild';function fake(bundle){bundle({entryPoints:['input.ts'],outfile:'fake.js'});}",'webpack.config.js':'// module.exports={entry:"input.ts",output:{filename:"fake.js"}};','input.ts':'export const value=1;'});expect(store.facts.some(fact=>fact.metadata.buildOutput||fact.kind==='module-dependency'&&fact.dependencyKind==='build-entry')).toBe(false);});
 it('keeps identical entry and output names within their own build project',async()=>{const fixture=toolCoverageFixtures.find(item=>item.stackId==='esbuild')!;const store=await scan(Object.fromEntries(['a','b'].flatMap(prefix=>Object.entries(fixture.sources).map(([path,source])=>[`${prefix}/${path}`,source]))));const inputs=store.facts.filter(fact=>fact.kind==='module-dependency'&&fact.dependencyKind==='build-entry');expect(inputs).toHaveLength(2);for(const input of inputs)if(input.kind==='module-dependency')expect(input.sourcePath.split('/')[0]).toBe(input.targetPath.split('/')[0]);});
});
