import type ts from'typescript';
import type{ExpansionContext}from'./expandedScan';
import{localPath}from'./projectPaths';
import{moduleIdForPath,parseModuleImports}from'./moduleResolver';
import{addProviderResource}from'./providerAdapters';
import{commandArgv,commandSourceRange,parseCommandExpression}from'./commandParser';

/** Static build inputs/outputs are declarations, not runtime modules or executed builds. */
export async function scanBuildConfiguration(context:ExpansionContext){
 context.builder.forEachFact(script=>{if(script.kind!=='package-script')return;for(const fragment of parseCommandExpression(script.command)){const argv=commandArgv(fragment);if(argv[0]!=='esbuild')continue;const inputArgs=argv.slice(1).filter(value=>!value.startsWith('-')&&/\.[cm]?[jt]sx?$/.test(value));const inputs=inputArgs.map(value=>localPath(script.packagePath,value)).filter((path):path is string=>Boolean(path&&context.sources.has(path)));const outputs=argv.filter(value=>/^--(?:outfile|outdir)=/.test(value));const range=commandSourceRange(context.sources.get(script.sourcePath)??'',script,fragment);for(const output of outputs){const id=addProviderResource(context,{stackId:'esbuild',path:script.sourcePath,...range,name:`esbuild output · ${output.slice(output.indexOf('=')+1)}`,type:'other',environment:'build',role:'deployment',attributes:{buildOutput:true,buildInvocationScriptId:script.id,outputPath:output.slice(output.indexOf('=')+1),outputKind:output.startsWith('--outfile=')?'file':'directory',inputPaths:inputs}});for(const input of inputs)context.relation(moduleIdForPath(input),id,'uses-config',[context.evidence(script.sourcePath,range.start,range.end,'build-input-output','esbuild CLIのentry/output宣言','declaration')],{buildInputOutput:true});}}});
 const explicitWebpack=new Set<string>();context.builder.forEachFact(script=>{if(script.kind!=='package-script')return;for(const fragment of parseCommandExpression(script.command)){const argv=commandArgv(fragment);if(argv[0]!=='webpack')continue;const index=argv.indexOf('--config');const value=index>=0?argv[index+1]:argv.find(item=>item.startsWith('--config='))?.slice(9);const path=value?localPath(script.packagePath,value):undefined;if(path)explicitWebpack.add(path);}});
 const candidates=[...context.sources].filter(([path,source])=>explicitWebpack.has(path)||/^webpack\.config\.[cm]?[jt]s$/.test(path.split('/').at(-1)!)||/\.[cm]?[jt]s$/.test(path)&&parseModuleImports(source).some(item=>item.specifier==='esbuild'));
 if(!candidates.length)return;const typescript=await import('typescript');
 for(const[path,source]of candidates){const file=typescript.createSourceFile(path,source,typescript.ScriptTarget.Latest,true,typescript.ScriptKind.TS);const host:ts.CompilerHost={getSourceFile:name=>name===path?file:undefined,getDefaultLibFileName:()=>'',writeFile:()=>{},getCurrentDirectory:()=>'',getDirectories:()=>[],fileExists:name=>name===path,readFile:name=>name===path?source:undefined,getCanonicalFileName:name=>name,useCaseSensitiveFileNames:()=>true,getNewLine:()=> '\n'};const checker=typescript.createProgram([path],{noLib:true,noResolve:true,allowJs:true},host).getTypeChecker();
  const imports=new Map<ts.Symbol,{name:string;module:string}>();for(const statement of file.statements){if(!typescript.isImportDeclaration(statement)||!typescript.isStringLiteralLike(statement.moduleSpecifier)||statement.importClause?.isTypeOnly)continue;const clause=statement.importClause;const register=(name:ts.Identifier,imported:string)=>{const symbol=checker.getSymbolAtLocation(name);if(symbol)imports.set(symbol,{module:(statement.moduleSpecifier as ts.StringLiteralLike).text,name:imported});};if(clause?.name)register(clause.name,'default');if(clause?.namedBindings){if(typescript.isNamespaceImport(clause.namedBindings))register(clause.namedBindings.name,'*');else for(const member of clause.namedBindings.elements)if(!member.isTypeOnly)register(member.name,member.propertyName?.text??member.name.text);}}
  const resolve=(expression:ts.Expression,seen=new Set<ts.Symbol>()):ts.Expression=>{if(!typescript.isIdentifier(expression))return expression;const symbol=checker.getSymbolAtLocation(expression);if(!symbol||seen.has(symbol))return expression;const declaration=symbol.valueDeclaration;return declaration&&typescript.isVariableDeclaration(declaration)&&declaration.initializer?resolve(declaration.initializer,new Set([...seen,symbol])):expression;};
  const configs:{product:'webpack'|'esbuild';options:ts.ObjectLiteralExpression}[]=[];
  const webpack=explicitWebpack.has(path)||/^webpack\.config\.[cm]?[jt]s$/.test(path.split('/').at(-1)!);
  const visit=(node:ts.Node)=>{if(webpack&&typescript.isExportAssignment(node)){const options=resolve(node.expression);if(typescript.isObjectLiteralExpression(options))configs.push({product:'webpack',options});}
   if(webpack&&typescript.isBinaryExpression(node)&&node.operatorToken.kind===typescript.SyntaxKind.EqualsToken&&node.left.getText(file)==='module.exports'){const root=typescript.isPropertyAccessExpression(node.left)?node.left.expression:undefined;if(root&&!checker.getSymbolAtLocation(root)){const options=resolve(node.right);if(typescript.isObjectLiteralExpression(options))configs.push({product:'webpack',options});}}
   if(typescript.isCallExpression(node)){const root=typescript.isPropertyAccessExpression(node.expression)?node.expression.expression:node.expression;const symbol=checker.getSymbolAtLocation(root);const binding=symbol?imports.get(symbol):undefined;const method=typescript.isPropertyAccessExpression(node.expression)?node.expression.name.text:binding?.name;if(binding?.module==='esbuild'&&['build','buildSync','context'].includes(method??'')){const options=node.arguments[0]?resolve(node.arguments[0]):undefined;if(options&&typescript.isObjectLiteralExpression(options))configs.push({product:'esbuild',options});}}
   typescript.forEachChild(node,visit);};visit(file);
  for(const{product,options}of configs){const property=(object:ts.ObjectLiteralExpression,name:string)=>{for(const member of [...object.properties].reverse()){if(typescript.isSpreadAssignment(member)||member.name&&typescript.isComputedPropertyName(member.name))return undefined;if(member.name&&(typescript.isIdentifier(member.name)||typescript.isStringLiteralLike(member.name))&&member.name.text===name)return typescript.isPropertyAssignment(member)?resolve(member.initializer):undefined;}return undefined;};const entry=property(options,product==='webpack'?'entry':'entryPoints');
   const literals=(value:ts.Expression|undefined):ts.StringLiteralLike[]=>{if(!value)return[];const resolved=resolve(value);if(typescript.isStringLiteralLike(resolved))return[resolved];if(typescript.isArrayLiteralExpression(resolved))return resolved.elements.flatMap(item=>{const element=resolve(item);return product==='esbuild'&&typescript.isObjectLiteralExpression(element)?literals(property(element,'in')):literals(element);});if(typescript.isObjectLiteralExpression(resolved))return resolved.properties.flatMap(member=>{if(!member.name||!typescript.isIdentifier(member.name)&&!typescript.isStringLiteralLike(member.name))return[];const value=property(resolved,member.name.text);return value&&product==='webpack'&&typescript.isObjectLiteralExpression(value)?literals(property(value,'import')):literals(value);});return[];};
   if(!entry)context.builder.addWarning({id:`warning:build-options:${path}:${options.pos}`,filePath:path,severity:"warning",message:`${product}のentry設定は未指定、または静的に確定できません。`});
   const owner=context.owner(path);const base=owner?.directory??'.';const inputPaths:string[]=[];
   for(const input of literals(entry)){const target=localPath(base,input.text);if(!target||!context.sources.has(target)||!context.builder.getFact(moduleIdForPath(target))){context.builder.addWarning({id:`warning:build-entry:${path}:${input.getStart(file)}`,filePath:path,severity:'warning',message:`${product} entryは未解決: ${input.text}`});continue;}inputPaths.push(target);const evidence=context.evidence(path,input.getStart(file),input.end,'build-entry',`${product}の明示entry → ${target}`,'declaration');context.technology(product,path,input.getStart(file),input.end,'usage','静的build entry設定');if(context.builder.getFact(moduleIdForPath(path))){context.builder.addFact({id:`build-entry:${path}:${input.getStart(file)}:${target}`,kind:'module-dependency',label:input.text,fromModuleId:moduleIdForPath(path),toModuleId:moduleIdForPath(target),sourcePath:path,targetPath:target,filePath:path,dependencyKind:'build-entry',specifier:input.text,evidenceIds:[evidence],metadata:{dictionaryStackId:product,buildEntry:true}});context.relation(moduleIdForPath(path),moduleIdForPath(target),'uses-config',[evidence],{dependencyKind:'build-entry'});}}
   const output=product==='webpack'?property(options,'output'):options;if(output&&typescript.isObjectLiteralExpression(output)){const fileOption=property(output,product==='webpack'?'filename':'outfile');const directoryOption=property(output,product==='webpack'?'path':'outdir');for(const declared of [fileOption,directoryOption].filter((value):value is ts.StringLiteralLike=>Boolean(value&&typescript.isStringLiteralLike(value)))){const id=addProviderResource(context,{stackId:product,path,start:declared.getStart(file),end:declared.end,name:`${product} output · ${declared.text}`,type:'other',environment:'build',role:'deployment',attributes:{buildOutput:true,outputPath:declared.text,inputPaths,outputKind:declared===fileOption?'file':'directory'}});for(const input of inputPaths)context.relation(moduleIdForPath(input),id,'uses-config',[context.evidence(path,options.getStart(file),options.end,'build-input-output','静的buildのentry/output設定','declaration')],{buildInputOutput:true});}}
  }
 }
}
