// @vitest-environment node
import{beforeAll,describe,expect,it}from'vitest';import{providerCoverageFixtures}from'./fixtures/stack-coverage/providers';import{stackSupportById}from'./stackRegistry';import{scanProjectFiles}from'./scan';import{projectStackMap,projectCommand}from'./projectors';import{semanticInput}from'./semantic/client';import{analyzeSemanticSources}from'./semantic/analyze';import{projectSemanticView}from'./semantic/project';import{initializeTestParser,testLanguage,testParser}from'./semantic/testRuntime';
beforeAll(initializeTestParser);
const scan=(sources:Record<string,string>)=>scanProjectFiles(Object.entries(sources).map(([relativePath,source])=>({relativePath,name:relativePath.split('/').at(-1)!,extension:'.'+relativePath.split('.').at(-1),size:source.length,readText:async()=>source})));
describe('service / deployment / CDN / emulator fixture binding',()=>{
 it.each(providerCoverageFixtures)('$fixtureId does not construct product resources from commented source/configuration',async fixture=>{const sources=Object.fromEntries(Object.entries(fixture.sources).map(([path,source])=>[path,path.endsWith('package.json')?source:/\.(?:html|vue|xaml)$/.test(path)?`<!-- ${source} -->`:/\.(?:ts|js|json|jsonc)$/.test(path)||path.endsWith('.firebaserc')?source.split('\n').map(line=>'// '+line).join('\n'):source.split('\n').map(line=>'# '+line).join('\n')]));const store=await scan(sources);expect(store.facts.some(fact=>fact.kind==='resource'&&fact.dictionaryStackId===fixture.stackId)).toBe(false);});
 it.each(providerCoverageFixtures)('$fixtureId keeps configuration/source provenance through its applicable views',async fixture=>{expect(stackSupportById.get(fixture.stackId)?.fixtureId).toBe(fixture.fixtureId);const store=await scan(fixture.sources);expect(projectStackMap(store).nodes.some(node=>node.metadata.stackId===fixture.stackId)).toBe(true);const analysis=await analyzeSemanticSources(semanticInput(store),testLanguage,undefined,testParser);
   const resources=store.facts.filter(fact=>fact.kind==='resource'&&fact.dictionaryStackId===fixture.stackId);expect(resources.length).toBeGreaterThan(0);for(const resource of resources){expect(resource.metadata.observed).not.toBe(true);expect(resource.evidenceIds.every(id=>store.evidence.some(at=>at.id===id&&Boolean(store.sources[at.filePath])))).toBe(true);}expect(projectSemanticView(analysis,'runtime-flow').nodes.some(node=>node.kind==='resource'&&node.attributes.dictionaryStackId===fixture.stackId)).toBe(true);expect(analysis.architecture?.nodes.some(node=>node.attributes.dictionaryStackId===fixture.stackId||node.architecture?.technologyNames.includes(fixture.stackId))).toBe(true);
   if(fixture.sourceOperation)expect(analysis.edges.some(edge=>['uses-resource','uses'].includes(edge.kind)&&analysis.nodes.find(node=>node.id===edge.target)?.attributes.dictionaryStackId===fixture.stackId)).toBe(true);
   if(fixture.stackId==='cloudflare-kv'){const namespaces=analysis.architecture!.nodes.filter(node=>node.architecture?.identity?.identifier==='coverage-namespace');expect(namespaces).toHaveLength(1);expect(namespaces[0]!.attributes.dictionaryStackId).toBe('cloudflare-kv');}
   if(fixture.command){const script=store.facts.find(fact=>fact.kind==='package-script')!;expect(script).toBeDefined();expect(projectCommand(store,script.id).nodes.some(node=>node.type==='command')).toBe(true);}
 });
 it.each(providerCoverageFixtures)('$fixtureId preserves repeated configuration occurrences and their project scopes',async fixture=>{const sources=Object.fromEntries(['a','b'].flatMap(prefix=>Object.entries(fixture.sources).map(([path,source])=>[`${prefix}/${path}`,source])));const store=await scan(sources);const stack=store.facts.find(fact=>fact.kind==='technology'&&fact.dictionaryStackId===fixture.stackId)!;for(const prefix of ['a','b'])expect(store.evidence.some(at=>at.filePath.startsWith(prefix+'/')&&stack.evidenceIds.includes(at.id))).toBe(true);});
});
