// @vitest-environment node
import{beforeAll,describe,expect,it}from'vitest';
import{scanProjectFiles}from'./scan';import{projectCommand,projectStackMap}from'./projectors';import{commandPurpose}from'./expandedCommands';import{analyzeSemanticSources}from'./semantic/analyze';import{semanticInput}from'./semantic/client';import{initializeTestParser,testLanguage,testParser}from'./semantic/testRuntime';import{toolCoverageFixtures}from'./fixtures/stack-coverage/tooling';
beforeAll(initializeTestParser);
const scan=(sources:Record<string,string>)=>scanProjectFiles(Object.entries(sources).map(([relativePath,source])=>({relativePath,name:relativePath.split('/').at(-1)!,extension:'.'+relativePath.split('.').at(-1),size:source.length,readText:async()=>source})));
async function analyze(sources:Record<string,string>){const store=await scan(sources);return{store,analysis:await analyzeSemanticSources(semanticInput(store),testLanguage,undefined,testParser)};}
const manifest=(command:string)=>JSON.stringify({name:'root',scripts:{verify:command}});
describe('runtime operand, cwd and test discovery boundaries',()=>{
 it('uses Java source after classpath options and leaves Python -c data operands unrelated',async()=>{const store=await scan({'package.json':manifest('java --class-path libs/helper.jar Main.java && python -c "print(1)" data.py'),'Main.java':'class Main{public static void main(String[] args){}}','data.py':'print("data")'});const runtime=store.facts.filter(fact=>fact.kind==='runtime');expect(runtime).toHaveLength(1);expect(runtime[0]!.metadata.entryPath).toBe('Main.java');const command=projectCommand(store);expect(command.nodes.some(node=>node.factId===runtime[0]!.id)).toBe(true);});
 it.each([['--directory','api/main.py'],['--project','main.py']])('keeps uv %s cwd semantics',async(flag,expected)=>{const store=await scan({'package.json':manifest(`uv ${flag} api run python main.py`),'api/pyproject.toml':'[project]\nname="api"','api/main.py':'print("api")','main.py':'print("root")'});const runtime=store.facts.find(fact=>fact.kind==='runtime')!;expect(runtime.metadata.entryPath).toBe(expected);expect(projectCommand(store).nodes.some(node=>node.factId===runtime.id)).toBe(true);});
 it('does not use feature/option values as command purpose',()=>{expect(commandPurpose(['cargo','build','--features','test'])).toBe('build');expect(commandPurpose(['cargo','test','--features','build'])).toBe('test');});
 it('requires the real Jest imported/global binding and accepts a named alias',async()=>{const{analysis}=await analyze({'package.json':'{"dependencies":{"jest":"30"}}','app.test.ts':"import{test as check}from'@jest/globals';function test(name,fn){fn();}test('fake',()=>1);check('real',()=>2);"});const entries=analysis.nodes.filter(node=>node.kind==='entry'&&node.attributes.test&&node.attributes.dictionaryStackId==='jest');expect(entries.map(node=>node.label)).toEqual(['test: real']);});
 it('applies pytest file discovery rather than promoting every same-name helper',async()=>{const{analysis}=await analyze({'api/pyproject.toml':'[project]\nname="api"\n[dependency-groups]\ndev=["pytest"]\n[tool.pytest.ini_options]\ntestpaths=["tests"]','api/helpers.py':'def test_helper(value):\n return value','api/tests/test_api.py':'def test_real():\n assert 1==1'});expect(analysis.nodes.filter(node=>node.kind==='entry'&&node.attributes.test).map(node=>node.path)).toEqual(['api/tests/test_api.py']);});
 it('connects the explicit .NET project runtime to actual Program top-level processing',async()=>{const fixture=toolCoverageFixtures.find(item=>item.stackId==='dotnet')!;const{analysis}=await analyze(fixture.sources);const runtime=analysis.nodes.find(node=>node.kind==='resource'&&node.attributes.dictionaryStackId==='dotnet')!;expect(analysis.edges.some(edge=>edge.source===runtime.id&&edge.kind==='runtime-entry'&&analysis.nodes.find(node=>node.id===edge.target)?.path==='apps/api/Program.cs')).toBe(true);});
 it('keeps Deno declared ownership without npm names or empty packages fallbacks',async()=>{const fixture=toolCoverageFixtures.find(item=>item.stackId==='deno')!;const{store,analysis}=await analyze(fixture.sources);expect(store.facts.some(fact=>fact.kind==='workspace-package'&&fact.label==='npm')).toBe(false);expect(projectStackMap(store).regions?.some(region=>region.label==='npm')).toBe(false);expect(analysis.architecture?.nodes.some(node=>node.label==='packages'&&node.architecture?.kind==='shared-code')).toBe(false);expect(analysis.architecture?.nodes.filter(node=>node.label==='@fixture/shared'&&['code-package','shared-code','application'].includes(node.architecture?.kind??''))).toHaveLength(1);});
});
