// @vitest-environment node
import{beforeAll,describe,expect,it}from'vitest';
import{toolCoverageFixtures}from'./fixtures/stack-coverage/tooling';
import{scanProjectFiles}from'./scan';
import{projectCommand,projectDependencies,projectStackMap,projectWorkspace}from'./projectors';
import{semanticInput}from'./semantic/client';
import{analyzeSemanticSources}from'./semantic/analyze';
import{initializeTestParser,testLanguage,testParser}from'./semantic/testRuntime';
import{stackSupportById}from'./stackRegistry';
beforeAll(initializeTestParser);
const scan=(sources:Record<string,string>)=>scanProjectFiles(Object.entries(sources).map(([relativePath,source])=>({relativePath,name:relativePath.split('/').at(-1)!,extension:'.'+relativePath.split('.').at(-1),size:source.length,readText:async()=>source})));
describe('runtime / tool / test fixture bindings',()=>{
  it.each(toolCoverageFixtures)('$fixtureId does not turn tool configuration alone into a running process',async fixture=>{const sources=Object.fromEntries(Object.entries(fixture.sources).map(([path,source])=>{if(/(?:package|composer|deno)\.json$/.test(path)){const value=JSON.parse(source);delete value.scripts;delete value.tasks;return[path,JSON.stringify(value)];}return[path,source];}));const store=await scan(sources);expect(store.facts.some(fact=>fact.kind==='runtime'&&fact.metadata.dictionaryStackId===fixture.stackId)).toBe(false);expect(store.facts.some(fact=>fact.metadata.observed===true)).toBe(false);});
  it.each(toolCoverageFixtures)('$fixtureId retains explicit command and project/dependency declarations',async fixture=>{expect(stackSupportById.get(fixture.stackId)?.fixtureId).toBe(fixture.fixtureId);const store=await scan(fixture.sources);expect(store.facts.some(fact=>fact.kind==='technology'&&fact.dictionaryStackId===fixture.stackId)).toBe(true);expect(projectStackMap(store).nodes.some(node=>node.metadata.stackId===fixture.stackId)).toBe(true);const script=store.facts.find(fact=>fact.kind==='package-script'&&fact.scriptName==='verify')!;expect(script).toBeDefined();const command=projectCommand(store,script.id);if(!fixture.runtime)expect(command.nodes.some(node=>node.metadata.stackId===(fixture.commandStack??fixture.stackId)||node.factId===`technology:${fixture.commandStack??fixture.stackId}`)).toBe(true);
    if(fixture.packageName){expect(store.relations.some(relation=>relation.kind==='depends-on'&&(relation.metadata.packageName===fixture.packageName||store.facts.some(fact=>fact.id===relation.targetId&&fact.kind==='external-package'&&fact.packageName===fixture.packageName)))).toBe(true);expect(projectDependencies(store).edges.length).toBeGreaterThan(0);}if(fixture.workspace)expect(projectWorkspace(store).edges.some(edge=>edge.kind==='matches')).toBe(true);
    if(fixture.runtime){const runtime=store.facts.find(fact=>fact.kind==='runtime'&&fact.metadata.dictionaryStackId===fixture.runtime)!;expect(runtime).toBeDefined();expect(command.nodes.some(node=>node.factId===runtime.id)).toBe(true);expect(runtime.metadata.observed).toBe(false);const analysis=await analyzeSemanticSources(semanticInput(store),testLanguage,undefined,testParser);expect(analysis.architecture?.nodes.some(node=>node.architecture?.kind==='application')).toBe(true);}
  });
  it.each(toolCoverageFixtures)('$fixtureId keeps repeated declared projects in distinct directory scopes',async fixture=>{const sources=Object.fromEntries(['a','b'].flatMap(prefix=>Object.entries(fixture.sources).map(([path,source])=>[`${prefix}/${path}`,source])));const store=await scan(sources);for(const prefix of ['a','b']){expect(store.facts.some(fact=>fact.kind==='package-script'&&fact.scriptName==='verify'&&fact.packagePath.startsWith(prefix))).toBe(true);expect(store.evidence.some(at=>at.filePath.startsWith(prefix)&&store.facts.some(fact=>fact.kind==='technology'&&fact.dictionaryStackId===fixture.stackId&&fact.evidenceIds.includes(at.id)))).toBe(true);}});
  it.each(toolCoverageFixtures.filter(fixture=>['jest','pytest','junit','cypress'].includes(fixture.stackId)))('$fixtureId separates explicit tests and their actual processing',async fixture=>{const store=await scan(fixture.sources);const analysis=await analyzeSemanticSources(semanticInput(store),testLanguage,undefined,testParser);const entries=analysis.nodes.filter(node=>node.kind==='entry'&&node.attributes.test&&node.attributes.dictionaryStackId===fixture.stackId);expect(entries.length).toBeGreaterThan(0);expect(entries.every(node=>node.group==='Tests')).toBe(true);expect(analysis.edges.some(edge=>edge.kind==='test-body'&&entries.some(node=>node.id===edge.source))).toBe(true);});
});
