const replacements: Array<[RegExp, string]> = [
  [/Server Side/gi, 'サーバーサイド'],
  [/Frontend/gi, 'フロントエンド'],
  [/React tree/gi, 'Reactツリー'],
  [/Browser DOM/gi, 'ブラウザDOM'],
  [/Three\.js scene/gi, 'Three.jsのシーン'],
  [/object graph/gi, 'オブジェクトグラフ'],
  [/data model/gi, 'データモデル'],
  [/data layer/gi, 'データ層'],
  [/access control/gi, 'アクセス制御'],
  [/security rules/gi, 'セキュリティルール'],
  [/server process/gi, 'サーバープロセス'],
  [/managed SQL database/gi, 'マネージドSQLデータベース'],
  [/quality check/gi, '品質チェック'],
  [/toolchain/gi, 'ツールチェーン'],
  [/metadata/gi, 'メタデータ'],
  [/endpoint/gi, 'エンドポイント'],
  [/transaction/gi, 'トランザクション'],
  [/collection/gi, 'コレクション'],
  [/driver/gi, 'ドライバ'],
  [/resource/gi, 'リソース'],
  [/server-side/gi, 'サーバー側'],
  [/client-side/gi, 'クライアント側'],
  [/source of truth/gi, '正となるデータ'],
  [/source code/gi, 'ソースコード'],
  [/test framework/gi, 'テストフレームワーク'],
  [/markup language/gi, 'マークアップ言語'],
  [/stylesheet language/gi, 'スタイルシート言語'],
  [/programming language/gi, 'プログラミング言語'],
  [/package manager/gi, 'パッケージマネージャ'],
  [/object storage/gi, 'オブジェクトストレージ'],
  [/relational database/gi, 'リレーショナルデータベース'],
  [/document database/gi, 'ドキュメントデータベース'],
  [/object database/gi, 'オブジェクトデータベース'],
  [/object-oriented/gi, 'オブジェクト指向'],
  [/json-like/gi, 'JSONに近い'],
  [/file-based/gi, 'ファイルベース'],
  [/development server/gi, '開発サーバー'],
  [/production bundle/gi, '本番向けバンドル'],
  [/component tree/gi, 'コンポーネントツリー'],
  [/remote data/gi, 'リモートデータ'],
  [/client state/gi, 'クライアント状態'],
  [/server state/gi, 'サーバー状態'],
  [/runtime validation/gi, '実行時検証'],
  [/responsive design/gi, 'レスポンシブデザイン'],
  [/single-file/gi, '単一ファイル'],
  [/open-source/gi, 'オープンソース'],
  [/managed backend/gi, 'マネージドバックエンド'],
  [/build[- ]tool/gi, 'ビルドツール'],
  [/build pipeline/gi, 'ビルドパイプライン'],
  [/API endpoint/gi, 'APIエンドポイント'],
  [/static assets?/gi, '静的アセット'],
  [/static content/gi, '静的コンテンツ'],
  [/\bassets?\b/gi, 'アセット'],
  [/\bstatic\b/gi, '静的'],
  [/\basset\b/gi, 'アセット'],
  [/plugin API/gi, 'プラグインAPI'],
  [/\bplugin\b/gi, 'プラグイン'],
  [/integrations?/gi, '連携'],
  [/integrated/gi, '統合型'],
  [/\bintegrate\b/gi, '連携'],
  [/\bprovide\b/gi, '提供'],
  [/\bsupport\b/gi, '対応'],
  [/pull request/gi, 'プルリクエスト'],
  [/unit test/gi, '単体テスト'],
  [/regression test/gi, '回帰テスト'],
  [/serverless/gi, 'サーバーレス'],
  [/\bmodern\b/gi, 'モダンな'],
  [/Web development/gi, 'Web開発'],
  [/production/gi, '本番'],
  [/development/gi, '開発'],
  [/\btooling\b/gi, '開発ツール'],
  [/\brouting\b/gi, 'ルーティング'],
  [/\bmiddleware\b/gi, 'ミドルウェア'],
  [/\brendering\b/gi, 'レンダリング'],
  [/\bcomponent\b/gi, 'コンポーネント'],
  [/\bstate\b/gi, '状態'],
  [/\brefetch\b/gi, '再取得'],
  [/\bfetch\b/gi, '取得'],
  [/\bcache\b/gi, 'キャッシュ'],
  [/\bloading\b/gi, '読み込み中'],
  [/\bstale\b/gi, '古い状態'],
  [/\bshape\b/gi, '形'],
  [/\bvalue\b/gi, '値'],
  [/\bschema\b/gi, 'スキーマ'],
  [/\bvalidator\b/gi, 'バリデータ'],
  [/\butility\b/gi, 'ユーティリティ'],
  [/\bspacing\b/gi, '余白'],
  [/\bcolor\b/gi, '色'],
  [/\bsession\b/gi, 'セッション'],
  [/\bcredential\b/gi, '認証情報'],
  [/\btoken\b/gi, 'トークン'],
  [/\bprovider\b/gi, 'プロバイダ'],
  [/\bdependencies\b/gi, '依存関係'],
  [/\bdependency\b/gi, '依存関係'],
  [/\bcommit\b/gi, 'コミット'],
  [/\bbranch\b/gi, 'ブランチ'],
  [/\bmerge\b/gi, 'マージ'],
  [/\bhistory\b/gi, '履歴'],
  [/\bmanaged\b/gi, 'マネージド'],
  [/\bdistributed\b/gi, '分散型'],
  [/\benvironment\b/gi, '環境'],
  [/\becosystem\b/gi, 'エコシステム'],
  [/\bworkflow\b/gi, 'ワークフロー'],
  [/\bhosting\b/gi, 'ホスティング'],
  [/\bplatform\b/gi, 'プラットフォーム'],
  [/\bnavigation\b/gi, 'ナビゲーション'],
  [/\bbrowser\b/gi, 'ブラウザ'],
  [/\bautomation\b/gi, '自動化'],
  [/\brepository\b/gi, 'リポジトリ'],
  [/\breview\b/gi, 'レビュー'],
  [/\bresponse\b/gi, 'レスポンス'],
  [/\brequest\b/gi, 'リクエスト'],
  [/\bevent\b/gi, 'イベント'],
  [/\bdocument\b/gi, 'ドキュメント'],
  [/\bbinary\b/gi, 'バイナリ'],
  [/\bbackup\b/gi, 'バックアップ'],
  [/\bsoftware\b/gi, 'ソフトウェア'],
  [/\buser\b/gi, 'ユーザー'],
  [/\bcode\b/gi, 'コード'],
  [/\binfrastructure\b/gi, 'インフラ'],
  [/\bmachine\b/gi, 'マシン'],
  [/\bformat\b/gi, '整形'],
  [/\bcontainer\b/gi, 'コンテナ'],
  [/\bregistry\b/gi, 'レジストリ'],
  [/\bimage\b/gi, 'イメージ'],
  [/\bfile\b/gi, 'ファイル'],
  [/\bobject\b/gi, 'オブジェクト'],
  [/\btable\b/gi, 'テーブル'],
  [/\bqueries\b/gi, 'クエリ'],
  [/\bquery\b/gi, 'クエリ'],
  [/\bindex\b/gi, 'インデックス'],
  [/\bconstraint\b/gi, '制約'],
  [/\bembedded\b/gi, '組み込み型'],
  [/\blocal\b/gi, 'ローカル'],
  [/\bcloud\b/gi, 'クラウド'],
  [/\bidentity\b/gi, '識別情報'],
  [/features?/gi, '機能'],
  [/applications?/gi, 'アプリケーション'],
  [/\bapplication\b/gi, 'アプリケーション'],
  [/\bdatabase\b/gi, 'データベース'],
  [/\bstorage\b/gi, 'ストレージ'],
  [/\bruntime\b/gi, 'ランタイム'],
  [/\bframework\b/gi, 'フレームワーク'],
  [/\blibraries?\b/gi, 'ライブラリ'],
  [/\bbuild\b/gi, 'ビルド'],
  [/\bdeploy\b/gi, 'デプロイ'],
  [/\bpreview\b/gi, 'プレビュー'],
  [/\bbundle\b/gi, 'バンドル'],
  [/\blockfile\b/gi, 'ロックファイル'],
  [/\bworkspace\b/gi, 'ワークスペース'],
  [/\bmonorepo\b/gi, 'モノレポ'],
  [/\bflow\b/gi, 'フロー'],
  [/\bservice\b/gi, 'サービス'],
  [/\btool\b/gi, 'ツール'],
  [/\bsource\b/gi, 'ソース'],
  [/\bproject\b/gi, 'プロジェクト'],
  [/\bprocess\b/gi, '処理'],
  [/\bserver\b/gi, 'サーバー'],
  [/\bscene\b/gi, 'シーン'],
  [/\bcamera\b/gi, 'カメラ'],
  [/\blight\b/gi, 'ライト'],
  [/\bmesh\b/gi, 'メッシュ'],
  [/\bmaterial\b/gi, 'マテリアル'],
  [/\bhost\b/gi, 'ホスト'],
  [/\btarget\b/gi, '対象'],
  [/\bengine\b/gi, 'エンジン'],
  [/\brow\b/gi, '行'],
  [/\bcolumn\b/gi, '列'],
  [/\brelation\b/gi, '関係'],
  [/\banalysis\b/gi, '解析'],
  [/\bcoding\b/gi, 'コーディング'],
  [/\brule\b/gi, 'ルール'],
  [/\bunit\b/gi, '単体'],
  [/\btest\b/gi, 'テスト'],
  [/\baccess\b/gi, 'アクセス'],
  [/\bcontent\b/gi, 'コンテンツ'],
  [/\bmethod\b/gi, '方法'],
  [/\bnetwork\b/gi, 'ネットワーク'],
  [/\btimer\b/gi, 'タイマー'],
  [/\bpackage\b/gi, 'パッケージ'],
  [/\bmodel\b/gi, 'モデル'],
  [/\bdata\b/gi, 'データ'],
  [/UI\s+コンポーネント/g, 'UIコンポーネント'],
  [/Web\s+アプリケーション/g, 'Webアプリケーション'],
  [/モダンな Web開発/g, 'モダンなWeb開発'],
];

export function presentText(value: string): string {
  return replacements
    .reduce((current, [pattern, replacement]) => current.replace(pattern, replacement), value)
    .replace(/([ぁ-んァ-ヶ一-龯々ー])\s+([ぁ-んァ-ヶ一-龯々ー])/g, '$1$2');
}
